### ISSUE TITLE
Setting object:set_properties({visual_size={x=1,y=1,z=1}) breaks animation

### ISSUE THREAD

**Issue by oilboi** [minetest/minetest#10017]
##### Minetest version
```
Minetest 5.3.0-dev-8fc9e7eb1 (Windows)
```

##### OS / Hardware
Operating system: Windows 10
CPU: Ryzen 3200G

GPU model: 8192MB ATI Radeon RX 580 Series (XFX Pine Group)
OpenGL version: 4.6

##### Summary
Setting object:set_properties({visual_size={x=1,y=1,z=1}) breaks animation.  Defaults to animation frame 0.

##### Steps to reproduce
Run ```self.object:set_properties({visual_size={x=1,y=1,z=1})``` on an entity that uses animations.

**Comment by sfan5** [comment]
Is this about model or sprite (texture) animation? Which visuals is this reproducible with?

**Comment by dcbrwn** [comment]
@oilboi can you give an example model with animations to reproduce the bug? This might help a lot

**Comment by SmallJoker** [comment]
Duplicate of #9129 which is a duplicate of #7781 which is a duplicate of #6572.

**Comment by paramat** [comment]
The resetting of model animation was fixed by https://github.com/minetest/minetest/commit/db7c262ee85c5bcae68354280848218dbf14bf55 which is before the commit you are on, so i guess this issue refers to sprite texture animation?

**Comment by hecktest** [comment]
https://github.com/minetest/minetest/commit/db7c262ee85c5bcae68354280848218dbf14bf55 doesn't fix my instance of the bug
![seizure](https://user-images.githubusercontent.com/42101236/84213903-2804c500-aac2-11ea-9e11-72f31f76b15c.gif)

**Comment by paramat** [comment]
Interesting, reopening the original issue.

**Comment by hecktest** [comment]
What if it's not the same bug?

**Comment by hecktest** [comment]
This should be fixed by #10021, please confirm

**Comment by sorcerykid** [comment]
I can confirm this is an issue, at least as recently as f51cf7c. In order to simulate rays emanating from the mirrorball in my nightclub, I change the scale the object using `set_properties()`. But that causes the animation of the rays (which is a continuous 360 rotation) to restart, giving a jerky appearance.

**Comment by hecktest** [comment]
f51cf7c is much older than #10021
