### ISSUE TITLE
language not change-able

### ISSUE THREAD

**Issue by SwissalpS** [minetest/minetest#12038]
##### Minetest version
```
Minetest 5.6.0-dev-163d3547e-dirty (Linux)
```

##### OS / Hardware

Operating system: Fedora 34
CPU: i7

##### Summary
No matter which language I change to, after relaunching client the menu is still in english.
Also in-game the mods are not translating.

##### Steps to reproduce
- go to advanced settings, search for 'lang' and change to one of es, de, fr....
- quit minetest and relaunch it

**Comment by rubenwardy** [comment]
How did you get Minetest? RPM, Snap, Flatpak, Appimage etc?

**Comment by SwissalpS** [comment]
git clone from this repo

**Comment by rubenwardy** [comment]
Do you have gettext installed and enabled?  You can find out with ./bin/minetest --version, it'll say `USE_GETTEXT=1`

**Comment by SwissalpS** [comment]
```
Using Irrlicht 1.9.0mt4
Using LuaJIT 2.1.0-beta3
BUILD_TYPE=RelWithDebInfo
RUN_IN_PLACE=1
USE_CURL=1
USE_GETTEXT=1
USE_SOUND=1
STATIC_SHAREDIR="."
STATIC_LOCALEDIR="locale"
```

**Comment by sfan5** [comment]
Please post the terminal output of `./bin/minetest --verbose --config <(echo language = de)`

**Comment by SwissalpS** [comment]
```
2022-02-02 20:27:21: INFO[Main]: Using relative paths (RUN_IN_PLACE)
2022-02-02 20:27:21: INFO[Main]: Detected share path: /home/sam/test/minetest/s550/minetest/bin/..
2022-02-02 20:27:21: INFO[Main]: Detected user path: /home/sam/test/minetest/s550/minetest/bin/..
2022-02-02 20:27:21: INFO[Main]: Detected cache path: /home/sam/test/minetest/s550/minetest/bin/../cache
2022-02-02 20:27:21: WARNING[Main]: Couldn't find a locale directory!
2022-02-02 20:27:21: INFO[Main]: minetest with SER_FMT_VER_HIGHEST_READ=29, BUILD_TYPE=RelWithDebInfo
2022-02-02 20:27:21: INFO[Main]: RUN_IN_PLACE=1
2022-02-02 20:27:21: INFO[Main]: USE_CURL=1
2022-02-02 20:27:21: INFO[Main]: USE_GETTEXT=1
2022-02-02 20:27:21: INFO[Main]: USE_SOUND=1
2022-02-02 20:27:21: INFO[Main]: STATIC_SHAREDIR="."
2022-02-02 20:27:21: INFO[Main]: STATIC_LOCALEDIR="locale"
2022-02-02 20:27:21: VERBOSE[Main]: httpfetch_init: parallel_limit=8
2022-02-02 20:27:21: INFO[Main]: Gettext: domainname="minetest" path="/home/sam/test/minetest/s550/minetest/bin/../locale"
2022-02-02 20:27:21: INFO[Main]: Message locale is now set to: LC_CTYPE=es_ES.UTF-8;LC_NUMERIC=C;LC_TIME=es_ES.UTF-8;LC_COLLATE=es_ES.UTF-8;LC_MONETARY=es_ES.UTF-8;LC_MESSAGES=es_ES.UTF-8;LC_PAPER=es_ES.UTF-8;LC_NAME=es_ES.UTF-8;LC_ADDRESS=es_ES.UTF-8;LC_TELEPHONE=es_ES.UTF-8;LC_MEASUREME
2022-02-02 20:27:21: INFO[Main]: NT=es_ES.UTF-8;LC_IDENTIFICATION=es_ES.UTF-8
2022-02-02 20:27:21: INFO[Main]: Searching worlds...
2022-02-02 20:27:21: INFO[Main]:   In /home/sam/test/minetest/s550/minetest/bin/../worlds: p_min p_full 
2022-02-02 20:27:21: INFO[Main]: 2 found.
2022-02-02 20:27:21: INFO[Main]: Using default world at [/home/sam/test/minetest/s550/minetest/bin/../worlds/world]
2022-02-02 20:27:21: INFO[Main]: Using default gameid [minetest]
2022-02-02 20:27:21: INFO[Main]: Audio: Global Initialized: OpenAL 1.1 ALSOFT 1.19.1, using OpenAL Soft
2022-02-02 20:27:21: INFO[Main]: Irrlicht: Irrlicht Engine version 1.9.0mt4
2022-02-02 20:27:21: INFO[Main]: Irrlicht: Linux 5.15.16-100.fc34.x86_64 #1 SMP Thu Jan 20 16:34:27 UTC 2022 x86_64
2022-02-02 20:27:22: INFO[Main]: Irrlicht: Using renderer: OpenGL 3.0
2022-02-02 20:27:22: INFO[Main]: Irrlicht: Mesa DRI Intel(R) HD Graphics 3000 (SNB GT2): Intel Open Source Technology Center
2022-02-02 20:27:22: INFO[Main]: Irrlicht: OpenGL driver version is 1.2 or better.
2022-02-02 20:27:22: INFO[Main]: Irrlicht: GLSL version: 1.3
2022-02-02 20:27:22: VERBOSE[Main]: Client: Configuring X11-specific top level window properties
2022-02-02 20:27:22: VERBOSE[Main]: Client: Setting Xorg window manager Properties
2022-02-02 20:27:22: VERBOSE[Main]: Client: Setting Xorg _NET_WM_PID extended window manager property
2022-02-02 20:27:22: VERBOSE[Main]: Client: Setting Xorg WM_CLIENT_LEADER property
2022-02-02 20:27:22: VERBOSE[Main]: Client: Configuring general top level window properties
2022-02-02 20:27:22: INFO[Main]: Waiting for other menus
2022-02-02 20:27:22: INFO[Main]: Waited for other menus
2022-02-02 20:27:22: INFO[Main]: Audio: Initialized: OpenAL 
2022-02-02 20:27:22: INFO[Main]: GUIEngine: Initializing Lua
2022-02-02 20:27:22: VERBOSE[AsyncWorker-0]: Loading and running script from /home/sam/test/minetest/s550/minetest/bin/../builtin/init.lua
2022-02-02 20:27:22: VERBOSE[AsyncWorker-1]: Loading and running script from /home/sam/test/minetest/s550/minetest/bin/../builtin/init.lua
2022-02-02 20:27:22: INFO[AsyncWorker-0]: Initializing Asynchronous environment
2022-02-02 20:27:22: VERBOSE[AsyncWorker-2]: Loading and running script from /home/sam/test/minetest/s550/minetest/bin/../builtin/init.lua
2022-02-02 20:27:22: INFO[AsyncWorker-1]: Initializing Asynchronous environment
2022-02-02 20:27:22: VERBOSE[AsyncWorker-3]: Loading and running script from /home/sam/test/minetest/s550/minetest/bin/../builtin/init.lua
2022-02-02 20:27:22: INFO[AsyncWorker-2]: Initializing Asynchronous environment
2022-02-02 20:27:22: INFO[Main]: SCRIPTAPI: Initialized main menu modules
2022-02-02 20:27:22: VERBOSE[Main]: Loading and running script from /home/sam/test/minetest/s550/minetest/bin/../builtin/init.lua
2022-02-02 20:27:22: INFO[AsyncWorker-3]: Initializing Asynchronous environment
2022-02-02 20:27:22: INFO[Main]: Searching worlds...
2022-02-02 20:27:22: INFO[Main]:   In /home/sam/test/minetest/s550/minetest/bin/../worlds: p_min p_full 
2022-02-02 20:27:22: INFO[Main]: 2 found.
2022-02-02 20:27:22: INFO[Main]: Audio: Error opening /home/sam/test/minetest/s550/minetest/bin/../games/minetest_game/menu/theme.0.ogg for decoding
2022-02-02 20:27:22: INFO[Main]: Audio: Error opening /home/sam/test/minetest/s550/minetest/bin/../games/minetest_game/menu/theme.1.ogg for decoding
2022-02-02 20:27:22: INFO[Main]: Audio: Error opening /home/sam/test/minetest/s550/minetest/bin/../games/minetest_game/menu/theme.2.ogg for decoding
2022-02-02 20:27:22: INFO[Main]: Audio: Error opening /home/sam/test/minetest/s550/minetest/bin/../games/minetest_game/menu/theme.3.ogg for decoding
2022-02-02 20:27:22: INFO[Main]: Audio: Error opening /home/sam/test/minetest/s550/minetest/bin/../games/minetest_game/menu/theme.4.ogg for decoding
2022-02-02 20:27:22: INFO[Main]: Audio: Error opening /home/sam/test/minetest/s550/minetest/bin/../games/minetest_game/menu/theme.5.ogg for decoding
2022-02-02 20:27:22: INFO[Main]: Audio: Error opening /home/sam/test/minetest/s550/minetest/bin/../games/minetest_game/menu/theme.6.ogg for decoding
2022-02-02 20:27:22: INFO[Main]: Audio: Error opening /home/sam/test/minetest/s550/minetest/bin/../games/minetest_game/menu/theme.7.ogg for decoding
2022-02-02 20:27:22: INFO[Main]: Audio: Error opening /home/sam/test/minetest/s550/minetest/bin/../games/minetest_game/menu/theme.8.ogg for decoding
2022-02-02 20:27:22: INFO[Main]: Audio: Error opening /home/sam/test/minetest/s550/minetest/bin/../games/minetest_game/menu/theme.9.ogg for decoding
2022-02-02 20:27:22: INFO[Main]: Audio: Error opening /home/sam/test/minetest/s550/minetest/bin/../games/minetest_game/menu/theme.ogg for decoding
2022-02-02 20:27:22: INFO[Main]: OpenALSoundManager: "/home/sam/test/minetest/s550/minetest/bin/../games/minetest_game/menu/theme" not found.
2022-02-02 20:27:22: INFO[Main]: OpenALSoundManager: "/home/sam/test/minetest/s550/minetest/bin/../games/minetest_game/menu/theme" not found.
2022-02-02 20:27:22: INFO[Main]: OpenALSoundManager: "/home/sam/test/minetest/s550/minetest/bin/../games/minetest_game/menu/theme" not found.
2022-02-02 20:27:22: INFO[Main]: OpenALSoundManager: "/home/sam/test/minetest/s550/minetest/bin/../games/minetest_game/menu/theme" not found.
Quit message received.
2022-02-02 20:27:27: INFO[Main]: Audio: Deinitializing...
2022-02-02 20:27:27: INFO[Main]: Audio: Deinitialized.
2022-02-02 20:27:27: INFO[Main]: GUIEngine: Deinitializing scripting
2022-02-02 20:27:27: INFO[Main]: Searching worlds...
2022-02-02 20:27:27: INFO[Main]:   In /home/sam/test/minetest/s550/minetest/bin/../worlds: p_min p_full 
2022-02-02 20:27:27: INFO[Main]: 2 found.
2022-02-02 20:27:27: INFO[Main]: Audio: Global Deinitialized.
2022-02-02 20:27:27: ERROR[Main]: Error writing configuration file: "/dev/fd/63"
2022-02-02 20:27:27: VERBOSE[Main]: httpfetch_cleanup: cleaning up

```

**Comment by SwissalpS** [comment]
I've figured out what the problem was: the `locale` directory isn't moved to the `minetest` directory from `build` location.
This happens when doing a shaddow build.

**Comment by SwissalpS** [comment]
reopened because it's still an issue :/ I was a bit overexcited that I had solved 'my' issue :p

**Comment by sfan5** [comment]
And how did you install/copy Minetest after building?

**Comment by Desour** [comment]
I've noticed this too, it happens when building out of tree.
You have to call cmake with `-DCUSTOM_LOCALEDIR=<your_build_dir>/locale`.
This is a bit annoying.

**Comment by SwissalpS** [comment]
> And how did you install/copy Minetest after building?

I built with flags: -DRUN_IN_PLACE=TRUE -DCMAKE_BUILD_TYPE=RelWithDebInfo

and thus run it in place.

**Comment by debagos** [comment]
@SwissalpS is this issue solved now?

**Comment by SwissalpS** [comment]
> is this issue solved now?

Nope. Still the same: locale dir stays in shaddow-build directory.
Nobody has stated that this is intentional or reasoned for locale directory not to be moved to where minetest expects it to be.

**Comment by rubenwardy** [comment]
I have this same problem, and have to manually move the locale directory to the correct place
