### ISSUE TITLE
Android - Drowning bubbles don't always show.

### ISSUE THREAD

**Issue by nanepiwo** [minetest/minetest#2205]
On Android builds (I am using 0.4.10 stable), often the bubbles that show that a player is in water are not shown. However, the player still loses HP if in water for too long.

**Comment by MoNTE48** [comment]
Confirm. The only problem for budget devices (<=1 GB RAM / 2 cores).

**Comment by nanepiwo** [comment]
This will hopefully be fixed in 0.5.0, since the roadmap (#2370) states that drowning will be calculated server-side.

**Comment by ShadowNinja** [comment]
That may or may not happen, but either way this has to be fixed.

**Comment by paramat** [comment]
@nanepiwo still a problem? There have been changes to damage.

**Comment by rubenwardy** [comment]
I can't reproduce this

**Comment by rubenwardy** [comment]
is this still a problem?

**Comment by paramat** [comment]
No responses for a long time, a new issue will be opened by someone if still a problem
