### ISSUE TITLE
Crashing mod crashes the server

### ISSUE THREAD

**Issue by neko259** [minetest/minetest#2507]
If mod tries to access a nil variable or something like that entire server crashes. Could you make it so that the crashed mod method just returned and threw an error, but the server (and the mod in general) continued working?

**Comment by nerzhul** [comment]
A pr was opened for this because my fix was incomplete.

**Comment by nerzhul** [comment]
#2506

**Comment by nerzhul** [comment]
Fixed 67b599666763dbc304023d531fa02f80c9527aa7

**Comment by neko259** [comment]
Will server still crash in this case? I don't understand what this change does.

**Comment by nerzhul** [comment]
Atm the throw is never catched because the server code isn't here. I also experienced your issue and it's coming in two cases:
* Lua mod critical bug
* Server could not bind to the requested address because another program does it.

If a Lua mod has a critical bug the only way to recover is to inform the player that the mod has a critical bug which needs to be fixed.

**Comment by neko259** [comment]
@nerzhul What do you mean by saying Lua bug is critical? This can be some condition in ABM that is triggered in 1/1000 times, and just skipping it can do no harm. It needs to be logged, but not crash server, IMO.

**Comment by nerzhul** [comment]
Lua errors are triggered by critical bugs which are similar to core segfaults. The situation is non recoverable

**Comment by neko259** [comment]
@nerzhul Do you mean it is non recoverable by code or non recoverable by our policy? I'm not familiar familiar to how lua is tied to minetest server so I need a clarification. In my imagination it is more like an OS kernel and applications -- applications can crash, but the kernel stays running forever and may even restart the applications.

**Comment by nerzhul** [comment]
imagine the following code:

player = null;
player->setHP(10);

we have a crash due to a null pointer. The LuaError triggered the ServerError this commit fixes in similar cases.

**Comment by neko259** [comment]
@nerzhul But why does the server need to be crashed in this case? Can we just skip the method that caused this (for example, it was triggered in on_use or ABM) and continue working with the rest of mod?

**Comment by nerzhul** [comment]
no because the following executed code may not be valid and the program can have some strange issues. The code must be fixed

**Comment by neko259** [comment]
It is definitely not valid. But improperly working server is better than no server at all. I cannot speed up mod devs to fix their issues and meantime my server gets crashed at night and no player can enter until I get up and restart it. I think there must be some way to bypass the error but can't say which one is the best (unload the mod causing problems, keep the mod running and skip the error or something other).

At least I think this issue needs to be open and up untile someone suggests some normal way.

**Comment by nerzhul** [comment]
This behavior was already there. I only fix a pure core crash not the Lua coding errors you have.
If you want you server to restart on fatal errors, please launch a shell script to restart it. This commit add the trace into your logs to fix the bug, then you can contact the mod owner to fix the bug you encounter.

**Comment by neko259** [comment]
> This commit add the trace into your logs to fix the bug

But there already was a trace of Lua error.

**Comment by nerzhul** [comment]
Then you can fix the error and have a long time running server. The bug i fixed there was a server crash without any log.

**Comment by neko259** [comment]
Oh, ok. But than your fix is not related to this issue at all. The issue is to make the server run without crash, not about log. Pls reopen it.

**Comment by nerzhul** [comment]
Sorry but if you try to access to a nil value and do something with it it's a LuaError exception because of a null pointer call. The mods must be fixed, we won't fix the core for a Lua only bug.

**Comment by neko259** [comment]
I don't say the mods must not be fixed. But what does enforcing server crash achieve?

**Comment by nerzhul** [comment]
because your issue cannot be executed and it's not recoverable you are trying to access to a non valid fragment of memory !

**Comment by neko259** [comment]
Is it not recoverable because we cannot do (the minetest engine does not allow) it or because we don't want it? Sorry, I didn't see an answer to this question. Please repeat it.

**Comment by nerzhul** [comment]
it's not a engine problem it's a pure algorithm problem. You are in a unrecoverable situation because you are trying to execute could in bad memory segments or in null memory segments which is not allowed by the OS.

**Comment by neko259** [comment]
So the server is tied to memory chunks that are allocated by Lua?

**Comment by neko259** [comment]
I just don't understand why can't we do something like:
try {
  callSomeLuaModCode();
catch (VeryBigErrorCrash) {
  doNothingAndProceed();
}

**Comment by nerzhul** [comment]
because it's ugly, bad, can cause more problems etc...

**Comment by neko259** [comment]
That's what I'm trying to understand here: why it this worse than crushing entire server with dozens of players and what can be called "more problems" than this.

**Comment by nerzhul** [comment]
If the missing code generate some missing parts of code which modify your player's experience and is save to database because some parts of code is missing, are you sure you want that ?

**Comment by neko259** [comment]
I am sure this is better than crash, yes.

But from your words I see that minetest does not use transactions and error in some part working with database can make it incomplete, which is very bad.

But it will be incomplete anyway, even if the server crashed. With no transactions and with every operation on the world working immediately, you will get the world "inconsistent" just the line before it crashed. So what do we solve by crashing then?

**Comment by nerzhul** [comment]
sometimes nothing, sometimes a thing. It depend of the code. I'm talking with @kwolekr and he said this is possible technically but will be disabled by default because it could be very dangerous

**Comment by neko259** [comment]
Well, that's something. I don't really care about the default, I just need a possibility to enable this on my server. Thanks you.

**Comment by ShadowNinja** [comment]
@neko259: We don't because fatal errors like this mean that the mod has a bug.  This means that ignoring the error is likely to result in more errors or even corruption (eg, there's an error when updating an area in my areas mod, the server ignores it, and when you shut down you get corrupt data which, which will lead to more errors in the future).  Also, consider a bug in on_globalstep:  It will print about 8-14 lines of text ten times a second.  You can'y just skip the globalstep because it might result in other bugs.

FreeMiner did this when I looked at it a while ago, except that it ignores 499 out of every 500 fatal errors, presumably because of the problems I pointed out.

**Comment by Megaf** [comment]
Aren't "bugs" like 
```
16:30:17: WARNING: Undeclared global variable "rulename" accessed at .../bin/../mods/minetest-mod-mesecons/mesecons/internal.lua:427
16:30:19: WARNING: Undeclared global variable "rulename" accessed at .../bin/../mods/minetest-mod-mesecons/mesecons/internal.lua:381
```
As dangerous as a "nil value"!?

**Comment by asl97** [comment]
@Megaf those should just be missing `local`,  it's like of like not using `var` when defining variable in javascript or using `global` before defining variable in python iirc
i wouldn't call them as dangerous as calling a non-existing or non-valid method/function

**Comment by ShadowNinja** [comment]
@Megaf: Perhaps, but they can't be fatal for compatibility's sake.
