### ISSUE TITLE
Issues with new network code

### ISSUE THREAD

**Issue by PilzAdam** [minetest/minetest#2524]
Here is a list of issues with @nerzhul's recent network related code rewrite:
- [x] HP bug (#2501)
- [ ] Flat player glitch
- [x] Packets intended to be send as unreliable are being sent as reliable instead
- [x] Packets are being copied before
- [x] Players being spawned at (0,0,0) if static spawnpoint is set
- [x] Test whether performance has increased / decreased

All core devs are free to edit this post to expand this list. Do not remove points, though.

**Comment by nerzhul** [comment]
third point is already fixed.

**Comment by nerzhul** [comment]
For point 5: it's not related to network, the network handling is perfect. The problem seems on player loading

**Comment by nerzhul** [comment]
Point 4 is fixed, i removed one copy, the last copy is mandatory for the current network stack which is multi thread

61f2d0ca3417b2a18a60015bf5423629d81bb754

**Comment by PilzAdam** [comment]
Why is the last point marked as done? Has anyone actual statistics about the performance of the old vs. the new code?

**Comment by kwolekr** [comment]
Point 3 is not fixed, we need to check all instances where unreliable block sending was used.  The one instance where I did happen to spot it by chance was fixed, but there might be more.

**Comment by nerzhul** [comment]
The actual code uses same bufferization method than old code with some little performance improvements (like string copy). The performance cannot be lesser or greater than previously.

**Comment by nerzhul** [comment]
@kwoelr the packet you find is the only packet with mixed reliable and unreliable. Other packets have a field to manage thé reliability into the packet opcodes files. Then it's fixed.

**Comment by VanessaE** [comment]
https://github.com/minetest/minetest/issues/2544 may also be related to this.

Furthermore, I am now seeing placement delays that I am certain were not there before.  For example in a totally idle test world (e.g. one I've been using for months in singleplayer, where I know precisely how it normally behaves), placing a few pipeworks pipes now shows a delay between placement and the auto-connect behavior (even though this code hasn't been touched in quite a while).

**Comment by nerzhul** [comment]
I suspect the new crafting code instead of network, because the network doesn't change, in this case, hopefully :)

**Comment by nerzhul** [comment]
I recheck a last time difference between old code and new and i'm sure the packet sent as reliable which needs to be sent as reliable in some cases and unreliable in others are now fixes.

@VanessaE is fixed in master now.

**Comment by paramat** [comment]
HP bug still present in latest dev, nerzhul is there any progress on this?

**Comment by nerzhul** [comment]
@paramat please give me more informations to understand how to reproduce the problem at this moment, without this information nothing is possible

**Comment by nerzhul** [comment]
Point 5: https://github.com/minetest/minetest/commit/470de10de3a4d864ce2808bb3778cf9abfbc560e

**Comment by paramat** [comment]
Details are in thread #2501.

**Comment by paramat** [comment]
This issue may br related to network commits, although i still need to bisect #2607

**Comment by paramat** [comment]
nerzhul, perhaps it's a good idea to slow down your work on network so that we can all focus on fixng the bugs instead and catch up. Currently bugs are being created faster than we are able to fix them.
Please could you bisect #2501 and try to fix that? I have given as much information as i can about that.
I will bisect #2607.

**Comment by paramat** [comment]
> please give me more informations to understand how to reproduce the problem at this moment, without this information nothing is possible

Hi nerzhul, i have discussed the HP bug with you in #2501, the information is already there. Can you reproduce it? it's easy to reproduce. Please could you help fix the bug, perhaps by bisecting to find the commit that caused it? Please could you slow down your work on network and focus more on fixing the bugs? Minetest has lots of bugs which are being created faster than we can fix them. I will bisect #2607.

**Comment by nerzhul** [comment]
@paramat where did you see i do some faster network coding, please look at the commit list :).

**Comment by nerzhul** [comment]
@paramat have you tried #2592 which seems interesting to solve the existing problem.

**Comment by paramat** [comment]
My post is not really relevant now and was unreasonable in places, sorry, deleted.

**Comment by kwolekr** [comment]
I'm having a really hard time reproducing the flat player glitch.  As of https://github.com/minetest/minetest/commit/bd0b469d3d212ae1407233bdb743bfcab31b4dc7 I feel confident enough with the new network code to finally close this issue.

There is still a performance regression due to all the extra copying overhead involved with NetworkPacket, but this will be addressed with moving to the new interface here https://github.com/minetest/minetest/pull/3013 for building and parsing packets.
