### ISSUE TITLE
Character conversion failed / <invalid wstring>

### ISSUE THREAD

**Issue by neoascetic** [minetest/minetest#2574]
I am unable to use Cyrillic symbols in the chat (however, it seems like other players are able):
![](https://cloud.githubusercontent.com/assets/725836/6885164/5ed790f0-d613-11e4-82c9-31f0b9086387.png)

Also, I am able to use multi-byte symbols in world's name, but unable to see them in worlds list:
![](https://cloud.githubusercontent.com/assets/725836/6885160/3a3177fc-d613-11e4-8d93-6a1eea969132.png)
#1682 is related. My OS is OSX.

**Comment by yo-we** [comment]
Same problem can appears with german umlauts + sz
äöü
ÄÖÜ
ß
and french accent letters:
éêèëàâäîïçôû
ÉÊÈËÀÂÄÎÏÇÔÛ

**Comment by Rui914** [comment]
On the console screen (F10) by using the Ctrl+V, you can paste the multi-byte characters.

**Comment by yo-we** [comment]
OK, so much for the work-around. Could you please tell me what I have to do to get a clean exchange game-game and IRC-game (either direction) without conversion fail or characters being omitted? French becomes very hard to read when the (seen from English "special") characters are missing. These are part of the writing system and not optional for correct understanding.

**Comment by est31** [comment]
@neoascetic can you try now again?

**Comment by neoascetic** [comment]
@est31 `<invalid wstring>`

**Comment by est31** [comment]
@neoascetic can you run minetest with the --info param and search for log messages with "Couldn't convert UTF-8 string"? Could you copy them here?

**Comment by neoascetic** [comment]
```log
2015-06-23 14:47:49: INFO[ServerThread]: WARNING: core.env:[...] is deprecated and should be replaced with core.[...]
2015-06-23 14:47:49: INFO[main]: Couldn't convert wstring 0x3f040000400400003804000032040000350400004204000000000000 into wstring
2015-06-23 14:47:49: ACTION[ServerThread]: CHAT: <singleplayer> <invalid wstring>
2015-06-23 14:47:51: INFO[ConnectionSend]: con(7/2)RunTimeouts(): Peer 1 has timed out. (source=peer->timeout_counter)
2015-06-23 14:47:51: INFO[main]: Audio: Deinitializing...
2015-06-23 14:47:51: INFO[main]: Audio: Deinitialized.
2015-06-23 14:47:51: INFO[main]: Server destructing
```

**Comment by bluebear94** [comment]
Can reproduce when playing on Japanese locale.

**Comment by est31** [comment]
@neoascetic can you say what you have entered into chat? @bluebear94 can you try the same thing as @neoascetic, and also post the "original" code you entered?

**Comment by bluebear94** [comment]
@est31 Actually, I observed the problem on the main menu.

**Comment by yo-we** [comment]
@est31 As long as there is no good testing procedure established, it does not create any sense to make modifications and/or close related issues... I looked through some of them and have the impression that there is no meaningful test in place: issues closed, people complain about the same problem afterwards. I understand that it is not a concern for English writing people. It isn't a big issue for German writers either. But many other languages rely on these so called "special" characters (they are not special to these writing systems anyway). How can I help to bring this subject to a good ending? By "good end" I mean: the 7 working everywhere, from anywhere and all characters from all entry sources (including IRC and in game chat of course) appearing correctly everywhere?

**Comment by est31** [comment]
@yo-we which issue do you mean in particular?

**Comment by neoascetic** [comment]
@est31 I entered a few Cyrillic letters. You may try to input "Привет мир" as an example.

**Comment by yo-we** [comment]
@est31 Sometimes, they meet and it is difficult to help if no developer can guide us :)
Sorry if my comment seems a bit harsh. I made some research and discover that copy/paste and chat related problems are partially far older than a year, closed and still present. Some blame Irrlicht, others the OS, and so on. Point is, that the user decides whether it works or not, and the developer decides, how to fix it, hopefully finding out why it does not work, before :))
 Anyway, maybe you can guide me to help to enhance the situation.
Personally, in Minetest, I can not use copy/paste (proposed as work around above). Nor inside, nor from outside. I can not successfully enter the "special" characters -- except in T-chat. As I wrote above, copy/paste does not work, which makes special characters available to me very much depend on the configuration of the computer I currently use. So much for the freedom of choice of language. Ever tried to write decent French without accents :) or Russian without Cyrillic letters? Already had to copy some Czech from Google translate into the chat and it totally ffailed? Especially, when you act as a moderator, this becomes a very huge problem. The game being a multi-user game, chat is not an option, but a part of it.

**Comment by est31** [comment]
@yo-we I'm german myself. copy & paste is a totally different issue than this one. Please don't mix a github issue tracker with a forum. Also, only ranting doesn't help at all to fixing the bug.

**Comment by yo-we** [comment]
Sorry if you take it like that. Was not my intention to hurt you. Any guidance?

**Comment by est31** [comment]
Well, if you know a way how to retrieve clipboard content on linux, it would be great. I've created an [irrlicht bug](http://sourceforge.net/p/irrlicht/bugs/435/) for it.

**Comment by bkav2015** [comment]
<h1>CKoc</h1><hr /><p><i>CKoc</i> is an <i>open project</i>, which is founded for <i>character conversion</i>s.</p><hr /><div><p><i>CKoc</i> is a <i>free software</i>, which is used for a <i>number of benefit</i>s.</p><ul><li><i>Document typing</i>s.</li><li><i>Charset conversion</i>s.</li><li><i>Language spelling</i>s.</li></ul><p>Besides of <i>creation</i>s, <i>CKoc</i> comes with a various <i>powerful feature</i>s.</p><ul><li>Multiple <i>conversion</i>s.</li><li><i>Macro</i>s are <i>logical</i>.</li><li>Trusted <i>algorithm</i>s.</li></ul><p>Any <i>opinion</i>, please send to the <i>project developer</i>.</p></div><hr /><p><i>CKoc</i> is an <i>open project</i>, which is created by <a href="http://ckoc.sourceforge.net/">CKoc</a>. All rights reserved.</p>

**Comment by 0-afflatus** [comment]
Retrieving content from either clipboard on Linux would be a piece of the proverbial in Python and does not require anything like qt. I don't understand why it's a big deal for Irrlicht. This is a major issue for me. I'm almost put off having any cyrillic users on my game, as it is tedious and often impossible to look words up and impossible to respond in any readable way as the text field doesn't recognise compose key sequences. It's embarrassing constantly missing accents from French and Spanish.

Much as I understand the need to discuss issues separately, the fix for this involves enabling copy / paste as well. (IIUC this is a Linux-specific issue?)

**Comment by est31** [comment]
Yes, copy paste is a linux specific issue, and an irrlicht bug, not minetest. Its tracked by #373 . The bug is fixed upstream, you just have to wait for the next irrlicht release.

**Comment by nerzhul** [comment]
Upsteam issue. And yes it's fixed in irrlicht 1.9 i can confirm, i use it with my MT modified version

**Comment by est31** [comment]
Ermm... 373 is the upstream issue, not this one.

People unfortunately still report this bug (last report was this month I think), its not fixed until we have a proper utf-8 chat protocol (see #2885).

**Comment by 0-afflatus** [comment]
> The bug is fixed upstream

I am very happy to hear that.

**Comment by neoascetic** [comment]
Seems like chat-related problem is fixed for me on the latest master. World name issue still there.

**Comment by neoascetic** [comment]
World name issue is fixed in the latest master. Thanks.

**Comment by neoascetic** [comment]
Ooops, still appears in ncurses terminal, thus reopen 

![2018-01-25 13 20 28](https://user-images.githubusercontent.com/725836/35385935-c7233072-01d2-11e8-99c1-32575b23437d.png)

**Comment by davisonio** [comment]
Still experiencing this issue on 5.3 stable on macOS. Unable to view cyrillic characters in server list, just shows as `<invalid wstring>`.
![Screenshot 2020-12-19 at 14 19 53](https://user-images.githubusercontent.com/5341072/102691559-441db780-4205-11eb-886f-248f2509619a.png)

**Comment by sfan5** [comment]
Can you check if this is fixed with #10879 merged?
