### ISSUE TITLE
Mouse seems laggy in 0.4.12 (and 0.4.11) on OSX

### ISSUE THREAD

**Issue by kanduvisla** [minetest/minetest#2697]
When I try to play MineTest on OSX the mouse seems 'laggy': it moves just like there is a hair or something in the optical sensor. It's not the game that lags, since other animations (like water and other player movements etc.) all seem to animate fine.

When I open the inventory menu or in-game menu the mouse works just fine. It only seems to happen when the mouse is used in-game (for looking around / navigating).

This happens in 0.4.12 and 0.4.11. In 0.4.10 the mouse works fine, so that's the version I'm currently sticking to.

System specs:
- OSX Yosemite 10.10.3
- Mid 2011 27" iMac
- 3.1Ghz intel core i5
- 8 GB 1333 Mhz DDR3
- AMD Radeon HD 6970M 1024 MB

**Comment by Megaf** [comment]
I can confirm that, I can confirm everything.

Another way to describe that is that the mouse hangs, stops moving, not the mouse, but the camera, you move the mouse, camera moves and soon after camera stops.

That seems to happen when the map around you is loading, when everything is loaded then it works fine.

OS X Yosemite 10.10.4 (14E17e)
Mid 2010 Macbook Pro 7,1
2,4 GHz Core2Duo
4 GB 1067MHz DDR3
NVIDIA GeForce 320M 256 MB

**Comment by rubenwardy** [comment]
Are you sure you don't have cinematic mode on? (F8)

**Comment by kanduvisla** [comment]
I've never used cinematic mode (never pressed F8): it's just the vanilla install. I can try if pressing F8 affects the behaviour.

**Comment by Zeno-** [comment]
If somebody wants to donate me a 15-inch 2.5GHz with Retina display Macbook pro, I'll debug it :-D

**Comment by mdoege** [comment]
As noted in the OS X build thread, this is a problem with the fps limiter on OS X. I think the commit that broke things was this: https://github.com/minetest/minetest/commit/1c21e391edeb7739935ca78250f066a60c369fc7

**Comment by Megaf** [comment]
I can confirm it has something to do with FPS.

The laggyness is gone when I use the following settings on
```
˜/Library/Application\ Support/minetest/minetest.conf
```
```
wanted_fps = 10
fps_max = 99999
viewing_range_nodes_min = 115
viewing_range_nodes_max = 115
```

**Comment by Megaf** [comment]
ok, the whole problem is around the fps_max thing. When it begins to limit the FPS it actually limits the camera movement.

**Comment by mdoege** [comment]
Yes, but what I don't understand is how that commit broke things exactly. Is it because of "limitFps() no longer calls device->run()"?

There have also been hints in the forums that this problem might affect Chromebooks, so this might not be an OS X bug exclusively.

**Comment by Shromm** [comment]
I have this same problem running Mavericks but I don't understand at all how to fix it.

**Comment by Megaf** [comment]
Folks, is the bug still present?
My macs power supply cable broke and I can no longer test it.
@mdoege

**Comment by mdoege** [comment]
Yes, the bug is still there in MT 0.4.14 (installed via homebrew).

**Comment by maciejczyzewski** [comment]
@Megaf solution works only with camera/mouse. There is also bug with "picking something"... after this operation, personage is blocked.

---

I am using OS X 10.11.6. By the way _github label_ **OSX** should be changed to **macOS**.

**Comment by echosa** [comment]
I also have this issue. I just downloaded the game and tried it out, and I experience this. OS X 10.11.6. Increasing the max fps did seem to help, but then my character gets stuck after moving around for a couple of minutes. Can't move, can't jump, can't fall (even if I break out the blocks underneath). I have to exit the game and enter again in order to move again for a few minutes before I get stuck again. Water, etc. keeps moving. I can look around with the mouse. Just can't walk, jump, or fall. Not sure if related. Let me know if I should create a new issue for that, or if it's related to this. (Anyone else experience that after increasing max fps to fix the random mouse lagginess/unresponsiveness?)

**Comment by echosa** [comment]
Regarding the inability to move, it seems like there's already a GitHub issue: https://github.com/minetest/minetest/issues/4274

**Comment by paramat** [comment]
@mdoege is the origianal bug of this issue (as opposed to #4274) still present?

@nerzhul why closed? Just curious.

**Comment by mdoege** [comment]
@paramat #4274 was a different bug (caused by -ffast-math) that has been fixed in git. So I have no idea why #2697 was closed, a bug which is caused by changes to the FPS limiter.

**Comment by nerzhul** [comment]
@paramat can't remember, maybe a wrong issue id ?

**Comment by kanduvisla** [comment]
The bug is still there on 0.4.16. Installed via homebrew on OSX 10.12.5

**Comment by Fixer-007** [comment]
Try with "fps_max = 0" in config

**Comment by kanduvisla** [comment]
yeah, that's slightly better, although It still kind of feels glitchy

**Comment by Megaf** [comment]
I think the issue is that Minetest for macOS is using an X server, XQuartz in this case, instead of using macOS's default "window server".

**Comment by tacotexmex** [comment]
Can the build config be made so that all macOS builds comes with `fps_max = 0 or something big like 200` preset in the configuration?

**Comment by tacotexmex** [comment]
Close the issue?

**Comment by SmallJoker** [comment]
Fixed in #7885.
