### ISSUE TITLE
[Request] minetest.register_tree

### ISSUE THREAD

**Issue by Rui-Minetest** [minetest/minetest#2907]
Example:

```
minetest.register_tree({
    tree_type = "treedef",
    sidelen = 16,
    fill_ratio = 0.005,
    biomes = {"grassland"},
    treedef = {
        axiom="FFFFFAFFBF",
        rules_a="[&&&FFFFF&&FFFF][&&&++++FFFFF&&FFFF][&&&----FFFFF&&FFFF]",
        rules_b="[&&&++FFFFF&&FFFF][&&&--FFFFF&&FFFF][&&&------FFFFF&&FFFF]",
        trunk="default:tree",
        leaves="default:leaves",
        angle=30,
        iterations=2,
        random_level=0,
        trunk_type="single",
        thin_branches=true,
        fruit_chance=10,
        fruit="default:apple"
    }
})
```

I want to use like minetest.register decoration.

This API will facilitate the spawn of the tree.

**Comment by kilbith** [comment]
How dealing correctly with that, seriously ? No serious description, nothing... you really think to get a deep consideration with that ?

All your issues are very unclear or unexplained : https://github.com/minetest/minetest/issues/created_by/Rui914

EDIT : description added.

**Comment by C1ffisme** [comment]
Hold on kilbith, as much as I agree, we don't just bomb people for being in a hurry.

@Rui914 Listen, Rui, we need you to start explaining your suggestions more clearly. Use at least one sentence in *Proper English*. Also, suggest how and why this would be added, pros and cons, or other things to get people to listen to you.

It takes more than just a name to start an issue, Rui.

**Comment by Rui914** [comment]
@kilbith 
@C1ffisme 
I'm sorry...
I will be careful from now on.

**Comment by paramat** [comment]
Rui914's English may not be good, and the first post is actualy fairly clear despite that.
Rui914 feel free to reopen this, if your English is not good tell us and we will understand.

**Comment by kilbith** [comment]
Again, to clarify : my comment was posted when there was no description at all.

**Comment by paramat** [comment]
Sorry kilbith.

**Comment by paramat** [comment]
However, with restraint this could be good to have, and i think there is an intention to add this feature, so re-opening.

**Comment by asl97** [comment]
imo, this as it is have very limited use.

this could be use to unify the sapling grow function if it include a sapling name, it could be use to bind a grow function to it (in node definition).
and instead of just the l-system, maybe include the use of a function for the grow function.

this would make bonemeal and fertilized soil kind of mods easier to make, although that might require other information to be included like chance of grow, special check function and other stuff so that it would be possible to make it so that bonemeal wouldn't always causing the sapling to grow but still allow premium_bonemeal to have 100% chance of causing the sapling to grow (if it pass the special check function).

things like crop would need another function though.

**Comment by RobertZenz** [comment]
@paramat The problem with L-System trees is not the time that it takes for them to be generated, that is fine and absolutely acceptable. The problem is the code behind `minetest.spawn_tree`, which is utterly slow because it performs lighting updates *every time* a tree is spawned, see #2151, which makes it quite unusable for mapgens.

**Comment by Rui914** [comment]
How is this?
```
minetest.register_tree({
	tree_type = "function",
	sidelen = 16,
	fill_ratio = 0.005,
	biomes = {"grassland"},
	on_glow = function(pos)
		default.grow_tree(pos)
	end
})
```

**Comment by paramat** [comment]
RobertZenz good point, we would need a variation of l-system that acts on the mapgen voxelmanip and doesn't update the map, RealBadAngel may be interested in doing this.
Rui914, 'default grow tree' is lua code so cannot be used during c++ mapgen, it's also far too slow.

**Comment by RealBadAngel** [comment]
@paramat that was already solved. you can simply spawn l-system tree sapling by mapgen.

**Comment by RobertZenz** [comment]
@RealBadAngel What I and paramat meant isn't solved, at least not as far as I know, see #2151. It's not about *using* `spawn_tree` from a Lua mapgen, it is about the fact that it is slow because every spawn triggers a lighting update.

**Comment by Sokomine** [comment]
A general function to add a tree would be fine. Right now, we do have several methods for getting them to appear in the world: mapgen itshelf (v6?), default.grow_tree and co which places the individual nodes using voxelmanip (but sadly with a local function so that using them in a lua voxelmanip mapgen is not possible), the schematics approach, L-system trees, and - last but not least - slow calls to add_node/set_node (old mods still do it that way).
Trees are a basic component of the game and frequently needed. They are important for creators of subgames.
Trees are placed by mapgen when the map is generated and again later on when their abm lets their sapling grow. They all consist of a trunk, leaves, sometimes a fruit. In rare cases, a second type of leaves may appear. Saplings to spawn the trees are generated from leaves. Leaves decay. Tree trunks can be crafted into wood.
A common function supplied with the node names of the tree parts (trunk, leaves, fruit, sapling) or at least with the textures for them plus a general model/shape in one of the known forms (be it code, a schematic, L-system) could be very helpful. Nodes to be used and shape ought to be seperate parameters so that the same tree shape/model can be used with diffrent nodes/textures and vice versa. The mod creator ought to be able to supply his tree in whatever way he knows best (code, schematic, L-system).
Mapgen mods need a way to spawn such trees without having to re-implement the entire tree functions.

**Comment by 0-afflatus** [comment]
Trees and other complex decorations are important for subgames. Much as I love moretrees, using biome_lib to place plants really slows the game down and provides an unnecessary extra (and somewhat complex) layer of code to mapgen. The feature I would miss is being able to use temperature and humidity values directly, to fine-tune placement of plants within each biome.

The clearest solution is to have minetest.register decoration accept l-system definitions, which I understand is already on the cards. I'm slowly catching up after a few months off, forgive me if I'm bumping this unnecessarily.

**Comment by paramat** [comment]
The decoration code is intended to be able to place l-system trees as decorations, some of the code is already in there, it's a case of someone getting around to doing it. This means l-system trees could be placed in bulk without a lighting update for each (the problem moretrees has which also creates shadow bugs).
