### ISSUE TITLE
Glitching through ceiling

### ISSUE THREAD

**Issue by BlockMen** [minetest/minetest#3045]
Since https://github.com/minetest/minetest/commit/5c3c965c1a6e1fb5957d441c2d04d8470b80d710 you can glitch through ceiling by using "sneaking glitch".

Can be tested by something like this and sneak glitching.
![screenshot_20150813_122704](https://cloud.githubusercontent.com/assets/3742497/9248062/084bd3f6-41b9-11e5-8bf0-e272de6a5b82.png)

**Comment by est31** [comment]
Confirmed.

**Comment by BlockMen** [comment]
Marking as blocker since it was introduced just recently. We shouldn't release with new and know bugs.

**Comment by BlockMen** [comment]
https://github.com/minetest/minetest/commit/7238df4c5952ed9eec491f424b8ca4b790cf7558

**Comment by kahrl** [comment]
Not fixed yet. In 0.4.13-dev-3304e1e, when you stand inside this structure and sneak + jump, you glitch through the ceiling: 
![screenshot_20150828_123120](https://cloud.githubusercontent.com/assets/630411/9544406/d5ee30b0-4d80-11e5-86ea-aae0e6e48809.png)

**Comment by kahrl** [comment]
Removing blocker label since 0.4.13 has already been released.

**Comment by BlockMen** [comment]
@jp could you test #3089 if it fixes #3400 aka #3045 for you?

**Comment by everamzah** [comment]
https://youtu.be/iNlXsGm5FO0?t=25m10s

**Comment by Fixer-007** [comment]
Can confirm, why nobody is looking at this gameplay bug?

**Comment by HybridDog** [comment]
@everamzah, the video is locked in Germany, but it can be watched using a proxy:
https://mo.proxfree.com/permalink.php?url=s54aaHA%2FaGsaD5vHs0QZLcUclS%2FcUxrnNZwEMCiA0I%2FNAfRVM2PgwQ5%2BK0wvxofxfIDq6waMoNIGrXSmZnNDDuOAtKk21T2MUEPyW%2B%2B%2BRlSclURY8%2Fau%2BpIKAHOPBzMK&bit=49

**Comment by paramat** [comment]
It's because of limited dev time.

**Comment by HybridDog** [comment]
>It's because of limited dev time. People need to help out to get stuff fixed.

l tried it without success:
https://github.com/minetest/minetest/pull/4180
How do you do it?

**Comment by everamzah** [comment]
Let go of sneak, if you're holding it, before you jump; but depress it again quickly and give yourself some time holding it before impact.

**Comment by HybridDog** [comment]
>Is it still blocked?

Yes, it is because of GEMA assumptions.

gif is very inefficient
http://bellard.org/bpg/animation.html

**Comment by everamzah** [comment]
At nearly a megabyte, I must agree.  If you're able to refine it any, please do.

I may try #3089 and see if it works, but find engine code is daunting.

**Comment by HybridDog** [comment]
>At nearly a megabyte, I must agree. If you're able to refine it any, please do.

there:
https://hybriddog.github.io/hairy-avenger/bpgs/sneakbug.html
the bpg file takes 50.3 kB

**Comment by Wuzzy2** [comment]
Can you aim to fix this bug for next release (0.4.15)? It had “blocker” status previously.

**Comment by sofar** [comment]
I can reproduce this. Makes for nice elevators.

**Comment by paramat** [comment]
Might be too late to fix before release, it's hard enough getting the priority bugs fixed in time.
Surely if 'sneak glitch' is enabled another cheaty bug is not much of a problem?

**Comment by Fixer-007** [comment]
This is annoying bug in game.

**Comment by Amaz1** [comment]
Yes, I think that this is a serious game-play breaking bug. The normal sneak glitch isn't too bad (though still not ideal), but this allows you to pass through a solid node, which really shouldn't be possible... I find this really annoying.

**Comment by Wuzzy2** [comment]
This bug is now probably fixed with the merge of https://github.com/minetest/minetest/pull/5327.

I can't reproduce this bug as of 46276414ed51d61dc29879ac85e861dc770d90da.

**Comment by paramat** [comment]
Thanks.
