### ISSUE TITLE
Minetest locks cursor to center of screen even if minetest window is not active.

### ISSUE THREAD

**Issue by red-001** [minetest/minetest#3507]
This bug happens when while minetest is loading an other window is open. If the minetest windows is also minimized minetest may crash or lock the cursor to the top left of the screen instead.

**Comment by gregorycu** [comment]
Are you able to elaborate on the platform you are on?

**Comment by RobertZenz** [comment]
I'm not seeing this problem on Ubuntu 14.04, as soon as the window loses the focus (may it be by switching windows or switching to a different workspace) the cursor is released.

**Comment by rubenwardy** [comment]
He uses Windows 7.

IRC Log: http://irc.minetest.ru/minetest-dev/2015-12-31#i_4489623

**Comment by red-001** [comment]
@gregorycu I use windows 7 x64

**Comment by neoascetic** [comment]
Same problem on OSX

**Comment by est31** [comment]
This might be upstream bug, idk.

**Comment by ShadowNinja** [comment]
Also reproduced in Gnome shell in #3619.

**Comment by red-001** [comment]
This has also happened in older minetest versions.

**Comment by neoascetic** [comment]
Any news?

**Comment by nerzhul** [comment]
it's also present on archlinux with gnome shell

**Comment by nerzhul** [comment]
It's not platform specific.

**Comment by ShadowNinja** [comment]
@nerzhul: It seems it is.  I've only heard of it happening on OSX, Windows, and Gnome Shell.  KDE, XFCE, etc work fine AFAIK.

**Comment by DonBatman** [comment]
This happened in Gnome for me. Since I upgraded to Gnome Ubuntu 16.04 it does not happen.

**Comment by yusf** [comment]
Can confirm it happening on OS X.

**Comment by yusf** [comment]
Couldn't this be quite easily resolved by copying the code that disables cursor lock when opening the main menu in-game?

**Comment by est31** [comment]
@yusf if you manage to come up with a solution that works for you it would be appreciated.

**Comment by davisonio** [comment]
Still happening on macOS and I had the same problem on Windows too. Is avoidable by using ESC before changing windows but largely still annoying.

**Comment by ShadowNinja** [comment]
Can't confirm on Windows 10 or KDE.

**Comment by nerzhul** [comment]
@ShadowNinja fullscreen or not ? i think it's an interesting parameter for this

**Comment by Fixer-007** [comment]
I think I experienced that bug few times on Windows 7 sp1

**Comment by SmallJoker** [comment]
```diff
 src/game.cpp | 7 +++----
 1 file changed, 3 insertions(+), 4 deletions(-)

diff --git a/src/game.cpp b/src/game.cpp
index ace6474..782c02b 100644
--- a/src/game.cpp
+++ b/src/game.cpp
@@ -2929,7 +2929,8 @@ void Game::toggleFullViewRange()
 
 void Game::updateCameraDirection(CameraOrientation *cam, float dtime)
 {
-	if ((device->isWindowActive() && noMenuActive()) || random_input) {
+	if ((device->isWindowActive() && device->isWindowFocused()
+			&& noMenuActive()) || random_input) {
 
 #ifndef __ANDROID__
 		if (!random_input) {
@@ -2954,9 +2955,7 @@ void Game::updateCameraDirection(CameraOrientation *cam, float dtime)
 			device->getCursorControl()->setVisible(true);
 #endif
 
-		if (!m_first_loop_after_window_activation)
-			m_first_loop_after_window_activation = true;
-
+		m_first_loop_after_window_activation = true;
 	}
 }
 ```
Tried to reproduce the bug a few times on my Windows machine. Could someone please be so nice and check if this fixes the problem?

**Comment by nerzhul** [comment]
@SmallJoker looking at functions names seems lgtm for the first part, for the second part, it's strange no ?

**Comment by yusf** [comment]
Did this solve the issue for Mac too?

**Comment by nerzhul** [comment]
I think yes. If you can test 😎

**Comment by neoascetic** [comment]
I confirm. The issue has been fixed, thanks, @nerzhul! Although, there is still an issue: when I am clicking on minetest's window title in order to move it on the screen, the game grabs the cursor and nasty things happen. Simply said, I am unable to move the window. Could we do something with it?

**Comment by nerzhul** [comment]
nice ! thanks

**Comment by tacotexmex** [comment]
@neoascetic Does that also happen when the cursor is unlocked by means of opening a menu or inventory? If so it's a somewhat rarer bug, which is still good though still a bug.

**Comment by neoascetic** [comment]
@tacotexmex no, everything is fine when in that case

**Comment by neoascetic** [comment]
![Here is the thing I am talking about](https://cloud.githubusercontent.com/assets/725836/26145796/1acc3298-3aee-11e7-83ab-61e84fe34f31.gif)

**Comment by tacotexmex** [comment]
I've seen this behavior in many Mac games unfortunately.
