### ISSUE TITLE
Sneak fails if digging torch or similar below your position.

### ISSUE THREAD

**Issue by Dragonop** [minetest/minetest#3589]
Sneak in the border of a node, place a torch in the side of such node, then dig it while on top and even if sneaking you will fall.
_Place the torch_:
![screenshot_20160118_171732](https://cloud.githubusercontent.com/assets/8084219/12401755/422d89aa-be07-11e5-9eff-accad62d22e6.png)
_Sneak on top of the node it is attached to:_
![screenshot_20160118_171747](https://cloud.githubusercontent.com/assets/8084219/12401769/5f8d5f5c-be07-11e5-865e-392290ea9c09.png)
_dig the torch_:
![screenshot_20160118_171751](https://cloud.githubusercontent.com/assets/8084219/12401778/6b1e146a-be07-11e5-924e-4fe14f086979.png)

**Comment by ExcaliburZero** [comment]
Here is a quick video showing the issue on a build based off of the latest commit:

https://youtu.be/s_hIMvK85wU

**Comment by Dragonop** [comment]
Thanks @ExcaliburZero.

**Comment by 0-afflatus** [comment]
I can confirm this on latest build.

**Comment by Dragonop** [comment]
Not really a big deal, but still it's a problem.

**Comment by paramat** [comment]
#5327 merged, this is probably fixed now.

**Comment by Wuzzy2** [comment]
I just tested this in 46276414ed51d61dc29879ac85e861dc770d90da.
The bug is NOT fixed.

If you stand on the wall, sneaking, and dig the torch, nothing happens.
But if you dig the torch while sneaking *and* attempt to move towards the edge, you will fall as soon as you dig the torch.

**Comment by paramat** [comment]
Fixed with new sneak code whether 'sneak glitch' is enabled or not.
