### ISSUE TITLE
Shift key doesn't always work correctly in OS X

### ISSUE THREAD

**Issue by echosa** [minetest/minetest#4531]
The shift key works fine for sneaking, but I've observed two potentially related issues:

1.) Trying to shift-click items in the inventory doesn't work. E.g. trying to quickly moves item into the crafting grid or into a chest.

2.) If I go into the console by pressing `/`, pressing shift inserts a space. If I try to type a node name, like `default:wood` it comes out `default :wood` because of the space inserted by pressing shift. Alternatively, I can just press `/` then press shift multiple times and end up with `/`.

**Comment by everamzah** [comment]
What operating system?  Sneak key works fine for me, but I have it bound to Z.  Shift+clicking inventory works regardless.

**Comment by echosa** [comment]
As stated in the title, OS X. Specifically OS X 10.11.6. The issue happens even in the minimal test game without any additional mods, so it shouldn't be a mod conflict or anything.

**Comment by everamzah** [comment]
Oh sorry.  Just out of strict curiosity, what happens if you bind something else to sneak, does Shift work properly then?

**Comment by echosa** [comment]
I just tried that in the minimal test game with no mods. Still doesn't work, and shift still inserts spaces when typing `/` commands.

**Comment by everamzah** [comment]
I wonder if it's an Irrlicht bug.

**Comment by est31** [comment]
@echosa if you know how to compile, can you download irrlicht and run its gui example, to test whether you get a space when you enter : there as well?

**Comment by echosa** [comment]
Sorry, I was away all last week. If I did this correctly, then shift is not an issue in Irrlicht itself. It took me a while to figure out how to get things built and compiled (there was a code change required, apparently), but I finally got the user interface demo running. As you can see in the screenshot, I was able to put `:` using the shift key without extra spaces. It's a bit hard to see, so I manually put some spaces between some other colons at the end, just for a visual difference. As you can see in the first set of colons, there are no spaces.

<img width="645" alt="screen shot 2016-09-26 at 12 26 50 pm" src="https://cloud.githubusercontent.com/assets/133786/18844893/e8b10f2e-83e4-11e6-8c52-535809d6b33a.png">

**Comment by est31** [comment]
@echosa which version of irrlicht did you download, and which version does your minetest ship with (you can find out that e.g. ingame in the esc menu)

**Comment by echosa** [comment]
The Irrlicht version I downloaded was 1.8.4. I don't see the Irrlicht version in my escape menu nor do I see an irrlicht file in the bundled application. Does that mean it's using the one that's built on my system, which would also be 1.8.4?

```
^_^ echosa@Saffron:/Applications/minetest.app $ find . -name *rrlicht*
^_^ echosa@Saffron:/Applications/minetest.app $ 
```

<img width="850" alt="screen shot 2016-09-26 at 12 36 23 pm" src="https://cloud.githubusercontent.com/assets/133786/18845216/58856b46-83e6-11e6-87e9-637c6dad5816.png">

**Comment by echosa** [comment]
Ok, I ran the binary manually from a terminal from within the app itself, adding the `--info` flag. It tells me:

```
2016-09-26 12:44:23: INFO[Main]: Irrlicht: Irrlicht Engine version 1.8.3
```

So, I'll grab that version of Irrlicht and try the examples again.

**Comment by echosa** [comment]
Same result with 1.8.3.

**Comment by est31** [comment]
Okay, seems to be no upstream bug then.

**Comment by est31** [comment]
@echosa can you edit the minetest source code and add

```c++

		actionstream << "Key event with key " << (u32)event.KeyInput.Key
			<< "; char=" << event.KeyInput.Char
			<< "; ctrl=" << event.KeyInput.Control
			<< "; shift=" << event.KeyInput.Shift
			<< std::endl;
```
inside src/guiChatConsole.cpp, in line 430, so that it reads:

```C++
	if(event.EventType == EET_KEY_INPUT_EVENT && event.KeyInput.PressedDown)
	{
		actionstream << "Key event with key " << (u32)event.KeyInput.Key
			<< "; char=" << event.KeyInput.Char
			<< "; ctrl=" << event.KeyInput.Control
			<< "; shift=" << event.KeyInput.Shift
			<< std::endl;
		// Key input
		if(KeyPress(event.KeyInput) == getKeySetting("keymap_console"))
		{
```

plus then can you paste the output when you enter something using the shift key, best a text like "MineTest" or something?

**Comment by echosa** [comment]
> plus then can you paste the output when you enter something using the shift key, best a text like "MineTest" or something?

I'm not sure I understand what you mean by that.

**Comment by echosa** [comment]
Oh, I get it now. Output coming soon.

**Comment by echosa** [comment]
This is the output when I type `/MineTest` followed by two `Escape` presses to close the chat and quit the app. Of course, what I saw in the chat area was `/ Mine Test`.

```
2016-09-26 13:24:58: ACTION[Main]: Key event with key 16; char=16; ctrl=0; shift=1
2016-09-26 13:24:58: ACTION[Main]: Key event with key 77; char=77; ctrl=0; shift=1
2016-09-26 13:24:58: ACTION[Main]: Key event with key 73; char=105; ctrl=0; shift=0
2016-09-26 13:24:59: ACTION[Main]: Key event with key 78; char=110; ctrl=0; shift=0
2016-09-26 13:24:59: ACTION[Main]: Key event with key 69; char=101; ctrl=0; shift=0
2016-09-26 13:24:59: ACTION[Main]: Key event with key 16; char=16; ctrl=0; shift=1
2016-09-26 13:25:00: ACTION[Main]: Key event with key 84; char=84; ctrl=0; shift=1
2016-09-26 13:25:00: ACTION[Main]: Key event with key 69; char=101; ctrl=0; shift=0
2016-09-26 13:25:00: ACTION[Main]: Key event with key 83; char=115; ctrl=0; shift=0
2016-09-26 13:25:00: ACTION[Main]: Key event with key 84; char=116; ctrl=0; shift=0
2016-09-26 13:25:04: ACTION[Main]: Key event with key 27; char=27; ctrl=0; shift=0
```

The interesting line is

```
2016-09-26 13:24:58: ACTION[Main]: Key event with key 16; char=16; ctrl=0; shift=1
```

Which occurs twice, once for each time I pressed shift (the M and the T in MineTest). That key event is resulting in a space, it seems.

**Comment by est31** [comment]
Yup that's exactly the line that is different for me. My output:

```
Key event with key 161; char=0; ctrl=0; shift=0
Key event with key 77; char=77; ctrl=0; shift=1
Key event with key 73; char=105; ctrl=0; shift=0
Key event with key 78; char=110; ctrl=0; shift=0
Key event with key 69; char=101; ctrl=0; shift=0
Key event with key 161; char=0; ctrl=0; shift=0
Key event with key 84; char=84; ctrl=0; shift=1
Key event with key 69; char=101; ctrl=0; shift=0
Key event with key 83; char=115; ctrl=0; shift=0
Key event with key 84; char=116; ctrl=0; shift=0
```

So *maybe* it is a bug with irrlicht (maybe its just different behaviour on OSX), but it seems irrlicht manages to work around the issue in its GUI code.

We could check for ascii printable characters (and ignore them) to fix this issue.

**Comment by neoascetic** [comment]
I guess #4057 is related

**Comment by echosa** [comment]
I still experience this bug, and it's becoming more irritating the more I play. :-( Is there anything else we can do here?

**Comment by nerzhul** [comment]
Fixed

**Comment by tacotexmex** [comment]
Finally, thank you!

**Comment by echosa** [comment]
@nerzhul Thanks! I no longer get extra spaces in the console when I type shift. However, shift-clicking items still doesn't transfer them between inventories (like from my inventory into a chest, or vice versa). Is that something that is supposed to work in Minetest, or is that just something I'm used to from Minecraft that doesn't work in Minetest?

**Comment by l2dy** [comment]
> [...] However, shift-clicking items still doesn't transfer them between inventories (like from my inventory into a chest, or vice versa). Is that something that is supposed to work in Minetest, or is that just something I'm used to from Minecraft that doesn't work in Minetest?

It works with a patch in irrlicht.

```diff
diff --git source/Irrlicht/MacOSX/CIrrDeviceMacOSX.mm source/Irrlicht/MacOSX/CIrrDeviceMacOSX.mm
index ad493fc..126ae73 100644
--- source/Irrlicht/MacOSX/CIrrDeviceMacOSX.mm
+++ source/Irrlicht/MacOSX/CIrrDeviceMacOSX.mm
@@ -1018,6 +1018,8 @@ bool CIrrDeviceMacOSX::run()
 
 			case NSLeftMouseDown:
 				ievent.EventType = irr::EET_MOUSE_INPUT_EVENT;
+				ievent.MouseInput.Shift = IsShiftDown;
+				ievent.MouseInput.Control = IsControlDown;
 				ievent.MouseInput.Event = irr::EMIE_LMOUSE_PRESSED_DOWN;
 				MouseButtonStates |= irr::EMBSM_LEFT;
 				ievent.MouseInput.ButtonStates = MouseButtonStates;
@@ -1026,6 +1028,8 @@ bool CIrrDeviceMacOSX::run()
 
 			case NSLeftMouseUp:
 				ievent.EventType = irr::EET_MOUSE_INPUT_EVENT;
+				ievent.MouseInput.Shift = IsShiftDown;
+				ievent.MouseInput.Control = IsControlDown;
 				MouseButtonStates &= !irr::EMBSM_LEFT;
 				ievent.MouseInput.ButtonStates = MouseButtonStates;
 				ievent.MouseInput.Event = irr::EMIE_LMOUSE_LEFT_UP;
@@ -1034,6 +1038,8 @@ bool CIrrDeviceMacOSX::run()
 
 			case NSOtherMouseDown:
 				ievent.EventType = irr::EET_MOUSE_INPUT_EVENT;
+				ievent.MouseInput.Shift = IsShiftDown;
+				ievent.MouseInput.Control = IsControlDown;
 				ievent.MouseInput.Event = irr::EMIE_MMOUSE_PRESSED_DOWN;
 				MouseButtonStates |= irr::EMBSM_MIDDLE;
 				ievent.MouseInput.ButtonStates = MouseButtonStates;
@@ -1042,6 +1048,8 @@ bool CIrrDeviceMacOSX::run()
 
 			case NSOtherMouseUp:
 				ievent.EventType = irr::EET_MOUSE_INPUT_EVENT;
+				ievent.MouseInput.Shift = IsShiftDown;
+				ievent.MouseInput.Control = IsControlDown;
 				MouseButtonStates &= !irr::EMBSM_MIDDLE;
 				ievent.MouseInput.ButtonStates = MouseButtonStates;
 				ievent.MouseInput.Event = irr::EMIE_MMOUSE_LEFT_UP;
@@ -1053,6 +1061,8 @@ bool CIrrDeviceMacOSX::run()
 			case NSRightMouseDragged:
 			case NSOtherMouseDragged:
 				ievent.EventType = irr::EET_MOUSE_INPUT_EVENT;
+				ievent.MouseInput.Shift = IsShiftDown;
+				ievent.MouseInput.Control = IsControlDown;
 				ievent.MouseInput.Event = irr::EMIE_MOUSE_MOVED;
 				ievent.MouseInput.ButtonStates = MouseButtonStates;
 				postMouseEvent(event,ievent);
@@ -1060,6 +1070,8 @@ bool CIrrDeviceMacOSX::run()
 
 			case NSRightMouseDown:
 				ievent.EventType = irr::EET_MOUSE_INPUT_EVENT;
+				ievent.MouseInput.Shift = IsShiftDown;
+				ievent.MouseInput.Control = IsControlDown;
 				ievent.MouseInput.Event = irr::EMIE_RMOUSE_PRESSED_DOWN;
 				MouseButtonStates |= irr::EMBSM_RIGHT;
 				ievent.MouseInput.ButtonStates = MouseButtonStates;
@@ -1068,6 +1080,8 @@ bool CIrrDeviceMacOSX::run()
 
 			case NSRightMouseUp:
 				ievent.EventType = irr::EET_MOUSE_INPUT_EVENT;
+				ievent.MouseInput.Shift = IsShiftDown;
+				ievent.MouseInput.Control = IsControlDown;
 				ievent.MouseInput.Event = irr::EMIE_RMOUSE_LEFT_UP;
 				MouseButtonStates &= !irr::EMBSM_RIGHT;
 				ievent.MouseInput.ButtonStates = MouseButtonStates;
@@ -1076,6 +1090,8 @@ bool CIrrDeviceMacOSX::run()
 
 			case NSScrollWheel:
 				ievent.EventType = irr::EET_MOUSE_INPUT_EVENT;
+				ievent.MouseInput.Shift = IsShiftDown;
+				ievent.MouseInput.Control = IsControlDown;
 				ievent.MouseInput.Event = irr::EMIE_MOUSE_WHEEL;
 				ievent.MouseInput.Wheel = [(NSEvent *)event deltaY];
 				if (ievent.MouseInput.Wheel < 1.0f)
```

**Comment by omarsgifford14** [comment]
Unfortunately I'm still having trouble with shift-clicking items in inventories. Is there any way to implement that patch or just remedy the problem?

**Comment by tacotexmex** [comment]
Regardless, this issue should be reopened as one out of two problems it describes has been solved.

**Comment by tacotexmex** [comment]
Actually @sfan5 closing this and fold into https://github.com/minetest/minetest/issues/9308 seems better as that issue is more precise.

**Comment by SmallJoker** [comment]
@tacotexmex You ninja'd me by 10 seconds. congratulations for that.
