### ISSUE TITLE
GUIs do not scale properly with custom screen DPI settings

### ISSUE THREAD

**Issue by bvanrosendale** [minetest/minetest#6521]
System:
Antergos (similar to Arch Linux)
i3wm
Lenovo Thinkpad x1 Yoga
2550x1440 screen

This is what I see when opening it on my system
![image](https://user-images.githubusercontent.com/6497430/31469469-a099a0f6-aeaf-11e7-9729-aa311daf1f45.png)

My first thought was that it was related to the size of the game, but opening other windows (i3 is tiling so this effectively made Minetest go to 1/4 of it's previous size) didn't actually change the size of the text
![image](https://user-images.githubusercontent.com/6497430/31469843-5b8e1f30-aeb1-11e7-8966-9b4f4a1cf9a2.png)

I haven't tested with other window managers at this point, but I can if necessary.

**Comment by SmallJoker** [comment]
Does this problem also occur with any other inventory and the main menu? If so, try tuning the setting `gui_scaling` with higher values (`1.2`, `1.5`).
https://github.com/minetest/minetest/blob/9a41a3d/minetest.conf.example#L827

**Comment by BitOfAByte** [comment]
Thanks for that info, but increasing it actually makes it worse. `gui_scaling 1.5`

![image](https://user-images.githubusercontent.com/6497430/31497501-4b15fca0-af2d-11e7-9e1a-76ad7ecfbfb5.png)

However, going the other way, `gui_scaling 0.75` is better, although a few things are cut off.

![image](https://user-images.githubusercontent.com/6497430/31497559-7d048a38-af2d-11e7-80c7-9b342d9969be.png)

`gui_scaling 0.6` is perfect on my system.

![image](https://user-images.githubusercontent.com/6497430/31497868-469e6c60-af2e-11e7-80ba-580e128498db.png)

I think this problem might stem from `xrandr --dpi 175` in my `~/.xinitrc`.

This is `gui_scaling 1` with `xrandr --dpi 100`

![image](https://user-images.githubusercontent.com/6497430/31498111-236854a8-af2f-11e7-81dd-b2a1bc2087ed.png)

The issue is that low DPI values like that makes everything else very hard to read on my tiny screen. Ideally, the settings box would scale up with the rest of the screen.

**Comment by BitOfAByte** [comment]
This is related to #4607, same core issue (GUI contents can be bigger than the GUI).

**Comment by paramat** [comment]
@stujones11 i suspect this was fixed by #7834 ?

**Comment by bvanrosendale** [comment]
@paramat This didn't fix the issue for me. Here is a screenshot from the "change keys" page. Same computer specs as above, using `xrandr --dpi 225` and minetest `gui_scaling 1`.

![image](https://user-images.githubusercontent.com/6497430/49535297-d0184d00-f891-11e8-96b1-d312e9b874fe.png)

I didn't play around with any different options or all the different menus, but I'll have more time to poke around when I'm done with exams in a week.

**Comment by rubenwardy** [comment]
Closing in favour of #11209
