### ISSUE TITLE
Android 0.4.17.1: Google Play Store build crash while loading singleplayer world

### ISSUE THREAD

**Issue by juozaspo** [minetest/minetest#7439]
##### Issue type

 - Bug report
 
##### Minetest version

Google Play Store store build of `0.4.17.1` (4a48cd57, Android), apk version `0.4.17.19`

##### OS / Hardware

Operating system: Android 7.0
CPU: HiSilicon Kirin 650 2.11 Ghz (aarch64), 8 cores

##### Summary

When loading singleplayer on Android, Minetest Play Store build crash to the phone interface while no crash log is written to `debug.txt` file, happens a bit later after creating `worlds/singleplayerworld/ipban.txt` file.
Adding `debug_log_level = verbose` to `minetest.conf` produces more information but still no crash log, showing that the last operation is only to hash some files, after that game exits to the phone interface w/o any meaningful message in the log file (`debug.txt`).

from debug.txt (w/o verbose flag):
```
2018-06-12 07:19:46: ERROR[Main]: Subgame specified in default_game [minetest] is invalid.
2018-06-12 07:19:51: WARNING[Main]: Irrlicht: Could not open file of texture: /storage/emulated/0/Minetest/textures/base/pack/server_flags_.png
2018-06-12 07:19:51: WARNING[Main]: BanManager: creating /storage/emulated/0/Minetest/worlds/singleplayerworld/ipban.txt
```
verbose debug.txt: https://pastebin.com/S8YUEq16

**P.s.** There's only `map_meta.txt` and `world.mt` in `worlds/singleplayerworld` folder, there're no subfolder `minimal` in directory `games`.
**Update:** There's a working beta version on Play Store. After confirming that the future non-beta release would be working this issue should be closed.
##### Steps to reproduce

1. Clean install Minetest from Google Play Store or delete data for Minetest app if it's already installed, update it if app version is older than `0.4.17.19`.
2. Remove or  rename/move (preferred) `Minetest` folder in your storage directory if it exists.
3. Start Minetest app, click on Start Singleplayer button.
4. Wait a moment and watch how Minetest crashes to phone interface.

**Comment by paramat** [comment]
Weird:
https://github.com/minetest/minetest/blob/9cc341e91face2c999a96e023ba43444c689164d/src/defaultsettings.cpp#L304

**Comment by paramat** [comment]
[minetest] is correct as the subgame to use.

**Comment by nerzhul** [comment]
strange... i removed minetest folder on the root sdcard and it works like a charm

**Comment by rubenwardy** [comment]
You need to delete Minetest game before reextracting it, sounds like it doesn't handle deleted files

**Comment by juozaspo** [comment]
As shown in description, it still fails after deleting/renaming entire Minetest folder in phone storage root. The folder where game assets (games, worlds, etc.) are stored.

**Comment by juozaspo** [comment]
Verbose debug: https://pastebin.com/S8YUEq16

**Comment by srifqi** [comment]
Using logcat, I get crash dump:
```
********** Crash dump: **********
Build fingerprint: 'samsung/j7eltexx/j7elte:6.0.1/MMB29K/J700FXXU4BQL1:user/release-keys'
pid: 7295, tid: 7307, name: MinetestNativeT  >>> net.minetest.minetest <<<
signal 7 (SIGBUS), code 1 (BUS_ADRALN), fault addr 0xdb673511
Stack frame #00 pc 003e6b36  /data/app/net.minetest.minetest-1/lib/arm/libminetest.so (_Z17murmur_hash_64_uaPKvij+61): Routine ??
??:0
Stack frame #01 pc 0028a8e9  /data/app/net.minetest.minetest-1/lib/arm/libminetest.so (_ZN16CCraftDefManager10initHashesEP8IGameDef+196): Routine ??
??:0
Stack frame #02 pc 00399f11  /data/app/net.minetest.minetest-1/lib/arm/libminetest.so (_ZN6ServerC1ERKNSt6__ndk112basic_stringIcNS0_11char_traitsIcEENS0_9allocatorIcEEEERK11SubgameSpecbbbP13ChatInterface+2864): Routine ??
??:0
Stack frame #03 pc 002b8219  /data/app/net.minetest.minetest-1/lib/arm/libminetest.so (_ZN4Game24createSingleplayerServerERKNSt6__ndk112basic_stringIcNS0_11char_traitsIcEENS0_9allocatorIcEEEERK11SubgameSpectPS6_+516): Routine ??
??:0
Stack frame #04 pc 002b275f  /data/app/net.minetest.minetest-1/lib/arm/libminetest.so (_ZN4Game4initERKNSt6__ndk112basic_stringIcNS0_11char_traitsIcEENS0_9allocatorIcEEEEPS6_tRK11SubgameSpec+198): Routine ??
??:0
Stack frame #05 pc 002b2639  /data/app/net.minetest.minetest-1/lib/arm/libminetest.so (_ZN4Game7startupEPbbP12InputHandlerPN3irr14IrrlichtDeviceERKNSt6__ndk112basic_stringIcNS6_11char_traitsIcEENS6_9allocatorIcEEEESE_SE_PSC_tRSC_S0_P11ChatBackendRK11SubgameSpecb+356): Routine ??
??:0
Stack frame #06 pc 002c38c7  /data/app/net.minetest.minetest-1/lib/arm/libminetest.so (_Z8the_gamePbbP12InputHandlerPN3irr14IrrlichtDeviceERKNSt6__ndk112basic_stringIcNS5_11char_traitsIcEENS5_9allocatorIcEEEESD_SD_SD_tRSB_R11ChatBackendS_RK11SubgameSpecb+198): Routine ??
??:0
Stack frame #07 pc 004510e9  /data/app/net.minetest.minetest-1/lib/arm/libminetest.so (_ZN14ClientLauncher3runER10GameParamsRK8Settings+2416): Routine ??
??:0
Stack frame #08 pc 0031ef9b  /data/app/net.minetest.minetest-1/lib/arm/libminetest.so (main+8186): Routine ??
??:0
Stack frame #09 pc 00383713  /data/app/net.minetest.minetest-1/lib/arm/libminetest.so (android_main+90): Routine ??
??:0
Stack frame #10 pc 0082f641  /data/app/net.minetest.minetest-1/lib/arm/libminetest.so: Routine std::vector<TouchScreenGUI::id_status, std::allocator<TouchScreenGUI::id_status> >::end() at /home/srifqi/android/android-ndk/sources/cxx-stl/gnu-libstdc++/4.9/include/bits/stl_vector.h:627
Stack frame #11 pc 0003fc8b  /system/lib/libc.so (_ZL15__pthread_startPv+30)
Stack frame #12 pc 0001a3ab  /system/lib/libc.so (__start_thread+6)
```

**Comment by sfan5** [comment]
Ah `murmur_hash`, this looks familiar.
ARM generally doesn't do unaligned accesses, so the algorithm has to be rewritten to use memcpy instead of directly dereferencing a pointer.

**Comment by juozaspo** [comment]
Using logcat I found that crashdumps and other logs are dumped to `/data/system/dropbox` directory that's not accessible by normal user. To read those logs you need a rooted phone.
Latest crash log (`data_app_native_crash@1528820209301.txt`):
```
Process: net.minetest.minetest
Flags: 0x3888be44
Package: net.minetest.minetest v19 (0.4.17.19)
Foreground: Yes
Lifetime: 7s
Build: HONOR/NEM-L21/HNNEM-H:7.0/HONORNEM-L21/C432B351:user/release-keys

*** *** *** *** *** *** *** *** *** *** *** *** *** *** *** ***
Build fingerprint: 'HONOR/NEM-L21/HNNEM-H:7.0/HONORNEM-L21/C432B351:user/release-keys'
Revision: '0'
ABI: 'arm'
pid: 23577, tid: 23594, name: MinetestNativeT  >>> net.minetest.minetest <<<
signal 7 (SIGBUS), code 1 (BUS_ADRALN), fault addr 0xcd8ad651
    r0 cd8ad651  r1 0000000a  r2 deadbeef  r3 96331fd2
    r4 0000000a  r5 00000008  r6 00000000  r7 e760c9f0
    r8 cd8ad659  r9 c26e8bc1  sl 489ea13d  fp cc30df20
    ip c6a4a793  sp e760c9d8  lr 5bd1e995  pc d11cbb36  cpsr 00030030

backtrace:
    #00 pc 003e6b36  /data/app/net.minetest.minetest-1/lib/arm/libminetest.so (_Z17murmur_hash_64_uaPKvij+61)
    #01 pc 0028a8e9  /data/app/net.minetest.minetest-1/lib/arm/libminetest.so (_ZN16CCraftDefManager10initHashesEP8IGameDef+196)
    #02 pc 00399f11  /data/app/net.minetest.minetest-1/lib/arm/libminetest.so (_ZN6ServerC1ERKNSt6__ndk112basic_stringIcNS0_11char_traitsIcEENS0_9allocatorIcEEEERK11SubgameSpecbbbP13ChatInterface+2864)
    #03 pc 002b8219  /data/app/net.minetest.minetest-1/lib/arm/libminetest.so (_ZN4Game24createSingleplayerServerERKNSt6__ndk112basic_stringIcNS0_11char_traitsIcEENS0_9allocatorIcEEEERK11SubgameSpectPS6_+516)
    #04 pc 002b275f  /data/app/net.minetest.minetest-1/lib/arm/libminetest.so (_ZN4Game4initERKNSt6__ndk112basic_stringIcNS0_11char_traitsIcEENS0_9allocatorIcEEEEPS6_tRK11SubgameSpec+198)
    #05 pc 002b2639  /data/app/net.minetest.minetest-1/lib/arm/libminetest.so (_ZN4Game7startupEPbbP12InputHandlerPN3irr14IrrlichtDeviceERKNSt6__ndk112basic_stringIcNS6_11char_traitsIcEENS6_9allocatorIcEEEESE_SE_PSC_tRSC_S0_P11ChatBackendRK11SubgameSpecb+356)
    #06 pc 002c38c7  /data/app/net.minetest.minetest-1/lib/arm/libminetest.so (_Z8the_gamePbbP12InputHandlerPN3irr14IrrlichtDeviceERKNSt6__ndk112basic_stringIcNS5_11char_traitsIcEENS5_9allocatorIcEEEESD_SD_SD_tRSB_R11ChatBackendS_RK11SubgameSpecb+198)
    #07 pc 004510e9  /data/app/net.minetest.minetest-1/lib/arm/libminetest.so (_ZN14ClientLauncher3runER10GameParamsRK8Settings+2416)
    #08 pc 0031ef9b  /data/app/net.minetest.minetest-1/lib/arm/libminetest.so (main+8186)
    #09 pc 00383713  /data/app/net.minetest.minetest-1/lib/arm/libminetest.so (android_main+90)
    #10 pc 0082f641  /data/app/net.minetest.minetest-1/lib/arm/libminetest.so
    #11 pc 00047983  /system/lib/libc.so (_ZL15__pthread_startPv+22)
    #12 pc 00019efd  /system/lib/libc.so (__start_thread+6)
```

**Comment by stujones11** [comment]
@nerzhul I uninstalled my own build and downloaded your from the play-store, now singleplayer is crashing for me with the same error. Something has obviously gone wrong since b5350e27ad7bc54a3a97db988119db83c67f96b3 or you did not package the right MTG hash. I did also use gcc and static STL for my build, although I doubt it would that.

**Comment by stujones11** [comment]
@nerzhul I suggest to do a fresh build, using a clean environment pulling everything from scratch like I have just done. Actually test the singleplayer mode then push to the play-store if all is well :)

**Comment by lhofhansl** [comment]
I can confirm this issue on my phone. (Android 8.1.0)

**Comment by stujones11** [comment]
I have just discovered that current master is crashing with this exact same `murmur_hash` error.
```
12 17:57:54.715 19737 19737 F DEBUG   : backtrace:
06-12 17:57:54.715 19737 19737 F DEBUG   :     #00 pc 003e6b36  /data/app/net.minetest.minetest-1/lib/arm/libminetest.so (_Z17murmur_hash_64_uaPKvij+61)
06-12 17:57:54.715 19737 19737 F DEBUG   :     #01 pc 0028a8e9  /data/app/net.minetest.minetest-1/lib/arm/libminetest.so (_ZN16CCraftDefManager10initHashesEP8IGameDef+196)
06-12 17:57:54.715 19737 19737 F DEBUG   :     #02 pc 00399f11  /data/app/net.minetest.minetest-1/lib/arm/libminetest.so (_ZN6ServerC1ERKNSt6__ndk112basic_stringIcNS0_11char_traitsIcEENS0_9allocatorIcEEEERK11SubgameSpecbbbP13ChatInterface+2864)
06-12 17:57:54.716 19737 19737 F DEBUG   :     #03 pc 002b8219  /data/app/net.minetest.minetest-1/lib/arm/libminetest.so (_ZN4Game24createSingleplayerServerERKNSt6__ndk112basic_stringIcNS0_11char_traitsIcEENS0_9allocatorIcEEEERK11SubgameSpectPS6_+516)
06-12 17:57:54.716 19737 19737 F DEBUG   :     #04 pc 002b275f  /data/app/net.minetest.minetest-1/lib/arm/libminetest.so (_ZN4Game4initERKNSt6__ndk112basic_stringIcNS0_11char_traitsIcEENS0_9allocatorIcEEEEPS6_tRK11SubgameSpec+198)
06-12 17:57:54.716 19737 19737 F DEBUG   :     #05 pc 002b2639  /data/app/net.minetest.minetest-1/lib/arm/libminetest.so (_ZN4Game7startupEPbbP12InputHandlerPN3irr14IrrlichtDeviceERKNSt6__ndk112basic_stringIcNS6_11char_traitsIcEENS6_9allocatorIcEEEESE_SE_PSC_tRSC_S0_P11ChatBackendRK11SubgameSpecb+356)
06-12 17:57:54.716 19737 19737 F DEBUG   :     #06 pc 002c38c7  /data/app/net.minetest.minetest-1/lib/arm/libminetest.so (_Z8the_gamePbbP12InputHandlerPN3irr14IrrlichtDeviceERKNSt6__ndk112basic_stringIcNS5_11char_traitsIcEENS5_9allocatorIcEEEESD_SD_SD_tRSB_R11ChatBackendS_RK11SubgameSpecb+198)
06-12 17:57:54.716 19737 19737 F DEBUG   :     #07 pc 004510e9  /data/app/net.minetest.minetest-1/lib/arm/libminetest.so (_ZN14ClientLauncher3runER10GameParamsRK8Settings+2416)
06-12 17:57:54.716 19737 19737 F DEBUG   :     #08 pc 0031ef9b  /data/app/net.minetest.minetest-1/lib/arm/libminetest.so (main+8186)
06-12 17:57:54.716 19737 19737 F DEBUG   :     #09 pc 00383713  /data/app/net.minetest.minetest-1/lib/arm/libminetest.so (android_main+90)
06-12 17:57:54.716 19737 19737 F DEBUG   :     #10 pc 0082f641  /data/app/net.minetest.minetest-1/lib/arm/libminetest.so
06-12 17:57:54.716 19737 19737 F DEBUG   :     #11 pc 00047ab3  /system/lib/libc.so (_ZL15__pthread_startPv+22)
06-12 17:57:54.716 19737 19737 F DEBUG   :     #12 pc 00019f55  /system/lib/libc.so (__start_thread+6)
```
This time it does not even reach the main menu, it crashes as soon as the loading reaches the end.

**Comment by stujones11** [comment]
I have started to bisect this from where I was reasonably sure it would still work and can confirm that 2c490dddc037d7d1cf211bbf28309e31b0abdadd is good, however, I won't be able to do much more until the weekend.

**Comment by juozaspo** [comment]
Tested `0.4.17.1` apk from github Releases page. Same issue as in play store version, crashing when attempting to load singleplayer, with `Minetest` folder in phone storage root deleted. Apk name is `Minetest-0.4.17.1-2.apk`

**Comment by stujones11** [comment]
> Same issue as in play store version

I would expect it to be the same apk file anyway. I suspect that nerzhul may have accidentally packaged 0.4.17 game with 0.5.0 engine but I cannot be sure of that.

I have found the commit that appears to introduce this `murmr_hash` error 122eed7a3449eead6f87f45f2eb55c11c3cf171e although I am not exactly sure why that would be.

**Comment by lhofhansl** [comment]
I suggest we pull MT from the playstore until this is fixed. This looks pretty bad :(

**Comment by Lourens-Rich** [comment]
Any news??? Please, read new reviews on Google Play

**Comment by paramat** [comment]
Should be removed until fixed.

**Comment by stujones11** [comment]
@nerzhul I would suggest at least reverting back to 0.4.16-stable if you are unable to correct this soon,

**Comment by paramat** [comment]
#7482 merged and accidently closed this.

**Comment by SmallJoker** [comment]
@paramat What issues are remaining? Both #7463 and #7482 fixed the crashes which are mentioned here.

**Comment by paramat** [comment]
Ok, i wasn't sure so was being cautious :) thanks.

**Comment by juozaspo** [comment]
The stable-0.4 branch and Play Store release both need to be updated, since it's only fixed in master. The latest version of Play Store release is still affected as it remains unpached until stable branch gets updated.

**Comment by paramat** [comment]
@nerzhul is working on it.

**Comment by rubenwardy** [comment]
This should be closed only when a working and tested fix is released

**Comment by sfan5** [comment]
My self compiled 0.4.17.1 build worked perfectly in singleplayer, the play store build is still broken however.

**Comment by paramat** [comment]
Hmm, so these recent Android bugfixes were not the issue then and It's something to do with the creation of the play store version? That's what i thought earlier. So Android bugfixes since 0.4.17.1 don't need adding it seems?

**Comment by juozaspo** [comment]
Tested the Play Store beta, working fine. As the PR above is now merged, non-beta Android release needs to be tested for this issue to be closed.

**Comment by paramat** [comment]
I think all is resolved now.
