### ISSUE TITLE
Mobile password change glitch

### ISSUE THREAD

**Issue by Extex101** [minetest/minetest#8253]
##### Issue type

 - Bug report
 
##### Minetest version

```
0.4.17.22
```

GPU model:
OpenGL version:

##### Summary

Using the android Google play store build
The change password formspec is broken and when pressing back Minetest crashes

##### Steps to reproduce

1. Join a server
2. Click change password
(The text fields will be unclickable along with the cancel button)
After pressing back Minetest will crash
##### NOTE:
This has been tested on two phones

**Comment by ClobberXD** [comment]
Can confirm that this bug exists on the latest play store version. The first field (old password) field is highlighted in green (indicating focus) but the cursor doesn't appear. None of the fields and buttons can be clicked, and the only way to exit the formspec is to press the phone's back button.

**Comment by stujones11** [comment]
This was fixed by #7483

**Comment by Extex101** [comment]
OK but I still can't change my password
Could you update the mobile app?

**Comment by rubenwardy** [comment]
That'll happen soon:tm:. This issue tracker is for the development version of Minetest, so things will be closed when they are fixed in the development version - we don't wait until a release to do so
