### ISSUE TITLE
[Android] Keyboard control broken on 5.x build

### ISSUE THREAD

**Issue by mxvin** [minetest/minetest#8879]
##### Minetest version

```
5.0.1.24 and 5.0.1.23
(F-Droid apks) - or Playstore 
```

##### OS / Hardware

Operating system: Android 9
CPU: ARM64 

GPU model: -
OpenGL version: -

##### Summary

- On newer 5.x version, I cannot use keyboard to make player move (Forward, Backward, Left, Right), but other key works (jump, inventory, sneak, etc) render keyboard usage for playing became useless.
- Trying to remap the problem key to another but not works.
- This problem cannot reproduce in older version of minetest (4.x)  On this case, I try 0.4.17.21 from F-Droid. Full control from Keyboard can be achieve. 
- Note: I can confirm this problem only on USB based Keyboard (Android USB OTG Capability). None of BT Based keyboard was tested (I don't have one). 
Also I'm not yet try this on latest commit.

##### Steps to reproduce

1. Install any 5.x build of minetest on Android
2. Plug in your USB keyboard to OTG-capable phone
3. Play, you will notice behavior I explained previously (Cannot walk (WASD), but can do any other actions)
4. Install old 4.x build of minetest
5. Repeat steps 2 and 3, but now using keyboard you can be play normally

**Comment by MuhdNurHidayat** [comment]
Reproducible on both of my phones

Minetest version:
5.0.0.23 (latest version on Google Play that is available on my side on both phones as of 9:50pm 23 October 2019 GMT+8)

OS / Hardware
Phone 1
Operating system: Android 6.0 (already on last update available for this device)
CPU: armv8l
GPU model: ARM Mali-T760
OpenGL version: OpenGL ES 3.1 v1.r7p0-02rel0.676427c8bf7f70ce736d81c97bd5cec8
Hardware details can be seen here: https://valid.x86.fr/a/nv9f7w

Phone 2
Operating system: Android 5.1.1 (already on last update available for this device)
CPU: armv7l
GPU model: Qualcomm Adreno (TM) 330
OpenGL version: OpenGL ES 3.0 V@84.0 AU@05.01.00.042.030 (CL@)
Hardware details can be seen here: https://valid.x86.fr/a/xun113

Keyboard tested:
Logitech K120 (USB keyboard)

Note: most people who use keyboard on Android are using USB because Bluetooth-based keyboard has input lags and because certain phone/tablet casing has integrated keyboard with appropriate USB ready to be inserted to their device (mini/micro-USB for older devices, USB-C for newer devices)

Most probably someone accidentally removed the binding when they're reworking the ingame navigation (from old 4 key to the new joystick-style)

**Comment by SmallJoker** [comment]
Last known good: https://github.com/minetest/minetest/commit/6dc7177a5
First known bad: https://github.com/minetest/minetest/commit/f9d1810b1

Please ask stu (https://forum.minetest.net/viewtopic.php?f=42&t=21526) whether he would be so nice to share the entire builds directory so that we can limit the commit range. Currently one of ~1100 individual commits can be the problem. That's a damn high number.

**Comment by srifqi** [comment]
I can confirm this, too. <kbd>W</kbd>, <kbd>A</kbd>, <kbd>S</kbd>, <kbd>D</kbd>, and <kbd>/</kbd> aren't working.

Device: Lenovo G40-30 80FY ([details](https://support.lenovo.com/us/en/solutions/pd100009))
Operating System: Android 8.1 (Android x86)

**Comment by MoNTE48** [comment]
@SmallJoker Okay, within 10 minutes I found the problem. I will release a fix when I have time. (And I didn't even need to check 1,100 commits.)

**Comment by MoNTE48** [comment]
That I fixed it. What's again?

**Comment by rubenwardy** [comment]
@mnh48 claims that this is still a problem, needs to be reproduced

**Comment by MoNTE48** [comment]
Link for the latest APK?
I can test it on Chromebook, too.

**Comment by rubenwardy** [comment]
Here: https://github.com/rubenwardy/minetest/releases/tag/5.3.0-rc3

They're also available in the play store if you opt-in to the beta

**Comment by MoNTE48** [comment]
Everything works for me. Where is the @mnh48 message?
App version, phone model and android version? Which keys do not work?
Without this information, it is worth treating the report as a troll.

**Comment by mnh48** [comment]
I reported that from "Minetest Unofficial" Discord server earlier this morning, because I use Discord more than any other platform.
![Screenshot_20200629-152744_Discord](https://user-images.githubusercontent.com/12217018/85985347-312be680-ba1d-11ea-9c70-257070c3d182.jpg)

Minetest app version: 5.3.0-dev (from Beta program on Google Play store)
Phone model: Samsung Galaxy S7 Edge (SM-G935F)
Android version: 8.0
Keyboard: Logitech K120 (USB keyboard)

the keys not working on my side were W, A, S, D, Space, other keys like inventory, function keys work fine

**Comment by MoNTE48** [comment]
@mnh48, oh, try the APK on the Ruben link.
It works for me. I fixed the existing problem and the fix was merged a few weeks ago.
Tested on Android 10 + a wired ROCCAT Isku FX keyboard, as well as on a Chromebook with all installed updates. No one broke it again, yet XD

**Comment by mnh48** [comment]
ok the APK version worked fine

maybe it's something to do with the play store beta version then (even though it's supposed to be the same cuz that is still from ruben)

though the Esc key kinda wonky, like as if it was pressed twice at one time, but that don't bother me that much

**Comment by MoNTE48** [comment]
I did not touch the Esc button, honestly 😂
I don’t know what is uploaded to Google Play. And I categorically do not support that an nrz account is used with a developer name that is not related to Minetest.net.
Screenshots do not correspond to the real game, the description just boasts that it is free and without ads.
There is not even a link to the official website or privacy policy.
Managing Android builds should be more open. So let's wait for the one who added the version to the GP and find out from him what he did :)

**Comment by rubenwardy** [comment]
I added it to Google play, and it was the exact same apks as I linked
