### ISSUE TITLE
v5.1.0 does not work on Android 10

### ISSUE THREAD

**Issue by BeeeWall** [minetest/minetest#9413]
##### Minetest version

```
5.1.0.25 (from F-Droid), tested on the build [here](https://github.com/The-Unstable-World/binary/commit/6483a8d71f1f2f0c6b03c9e4428f29cea5070213) as well
```

##### OS / Hardware

Operating system: Android 10
CPU: ARM64

##### Summary

The app crashes on startup, and does not extract any files. There is no log file, but logcat says `W/System.err(18706): java.io.FileNotFoundException: /storage/emulated/0/Minetest/minetest.conf.example: open failed: EACCES (Permission denied)`

##### Steps to reproduce

1. Get a device or launch the emulator with Android 10 (potentially older versions too, I don't know)
2. Install version 5.1.0 from F-Droid
3. Try to launch it

Bit of guesswork:
I don't know if it's just Android 10, but I'm guessing so, because Android 10 basically got rid of external storage access. Versions before 5.1.0 (which appears to be the first version targeting API 29) do work, making me think that's it. An easy way to test if that's it: change the target API from 29 to 28 and compile. If so, the way to fix it could likely be to change it from using the `Minetest` folder and instead use `getExternalFilesDir()` (not sure how to access that folder from C/C++ code). Of course, my guess could be wrong. (I'd test this out if I could, but unfortunately I can't.)

**Comment by sfan5** [comment]
fixed by #9410

**Comment by BeeeWall** [comment]
My bad, I searched issues but not PRs. Should I close this or leave it open until that is merged?

**Comment by SmallJoker** [comment]
Keep it open until it's fixed. In other cases I'd personally close the issue if there's already a PR to fix it.

**Comment by rubenwardy** [comment]
Fixed in master

**Comment by Sonickyle27** [comment]
I am still getting this issue with version 5.2.0 from F-Droid on Android 10 (LineageOS 17.1).

Opening minetest when a minetest config folder exists on the internal storage results in this:

 
```
07-05 02:07:00.543 E/Minetest(17025): 2020-07-05 02:07:00: ERROR[Main]: An unhandled exception occurred: Failed to open log file /storage/emulated/0/Minetest/debug.txt: Permission denied
```

If I rename the minetest config folder so that the app will generate a new one, minetest will get stuck on the loading screen with a loading bar. Once this bar completes, it starts again, and no minetest config folder is created. Logcat shoss this:

```
07-05 02:17:50.952 E/MinetestAssetCopy(18093): Copying file: /storage/emulated/0//Minetest/games/minetest_game/minetest.conf.example FAILED (couldn't open output file)
07-05 02:17:50.952 W/System.err(18093): java.io.FileNotFoundException: /storage/emulated/0/Minetest/games/minetest_game/minetest.conf.example: open failed: ENOENT (No such file or directory)
07-05 02:17:50.952 W/System.err(18093): 	at net.minetest.minetest.MinetestAssetCopy$copyAssetTask.doInBackground(MinetestAssetCopy.java:210)
07-05 02:17:50.952 W/System.err(18093): 	at net.minetest.minetest.MinetestAssetCopy$copyAssetTask.doInBackground(MinetestAssetCopy.java:85)
```

**Comment by rubenwardy** [comment]
We close issues when we fix them, not when the fix is released.

You can try 5.3.0-dev by installing the APK file from https://github.com/rubenwardy/minetest/releases/tag/5.3.0-rc3

Or you can wait another week for 5.3.0 to be released

**Comment by Sonickyle27** [comment]
Ah ok thanks, I didn't notice it was right right after 5.2.0 was released.
