### ISSUE TITLE
Sprite sheets don't work for entities

### ISSUE THREAD

**Issue by Wuzzy2** [minetest/minetest#9481]
##### Summary

The `sprite` entity visal is broken. The sprite visual no longer supports sprite sheets.

This is a regression from Minetest 5.1.1.

##### Steps to reproduce

* Play the `devtest` game
* Give yourself the entity spawner (`testtools:entity_spawner`)
* Punch to select entity type, place to spawn entity
* Spawn `experimental:yawsprite` or `experimental:armorball`

Expected: Displays a single sprite
Actual: Displays a sprite sheet

(Note: issue split from #9479)

**Comment by Wuzzy2** [comment]
There should be a label for regressions.

**Comment by paramat** [comment]
@SmallJoker to clarify your comment https://github.com/minetest/minetest/issues/9479#issuecomment-596124065
Were spritesheets and entity visuals bisected to being broken by the same commit?

**Comment by SmallJoker** [comment]
@paramat I reverted that particular commit and both issues were resolved.

**Comment by Wuzzy2** [comment]
I find no evidence that any of “both issues” were actually resolved.

Still happening in 0cb34ce158989b66ecd42257dbed6729a338ff1e.

**Comment by paramat** [comment]
I think SmallJoker means he reverted the commit in his testing.

**Comment by Wuzzy2** [comment]
Yes, you are absolutely right. I totally misunderstood SmallJoker.

**Comment by dcbrwn** [comment]
on it

**Comment by dcbrwn** [comment]
It renders ok now. Also what's "yawsprite"? It looks like minetest doesn't support this kind of visual yet, and in devtest game it's created just as "sprite" without any constraints on rotation.
