### ISSUE TITLE
Wielditem + mesh objects are extremely lit by default

### ISSUE THREAD

**Issue by DeltaNedas** [minetest/minetest#9636]
##### Minetest version
```
5.1.0 from f-droid
```

##### OS / Hardware
Operating system: Android 9
Samsung A20e
Shaders are unavailable (!)

##### Summary
On 5.1.0, entities have no lighting, at least with no shaders enabled.
See screenshot, player and a fake node from my mod:
![Screenshot](https://user-images.githubusercontent.com/39013340/79027858-655ddc80-7b7d-11ea-95b8-2728e02bcb61.jpg)
On 5.2.0, entities using wielditem visual are too bright. Players may still be affected.

##### Steps to reproduce
1. enter a world with no shaders enabled
2. set time to night
3. look in third person or at entities like falling sand far from torches

**Comment by Extex101** [comment]
I can confirm this on 5.0.0 google play version

**Comment by sfan5** [comment]
This has probably been fixed in the meantime, someone will need to reproduce in 5.2.0 for this to be an useful bugreport.

**Comment by SmallJoker** [comment]
Tested using regular falling nodes. The calculations work, problem is that the "light at position" calculation results in too bright sides:

![grafik](https://user-images.githubusercontent.com/1497498/79074481-fe5f3580-7cec-11ea-9fa3-a6a684127321.png)

**Comment by DeltaNedas** [comment]
huh, on 5.3.0 theyre too dark
player, falling sand and objects from my mod (using wielditem and mesh visuals) are almost pitch black at midnight

**Comment by DeltaNedas** [comment]
@SmallJoker it seems that your sand test is fixed, sand looks correct when falling from the torch

**Comment by SmallJoker** [comment]
@DeltaNedas Please have a look at the right part of the image. The entity is lit too much compared to the surrounding nodes. Regardless the shader settings - it still happens in current master.

**Comment by SmallJoker** [comment]
Closing in favour of #9877
